INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', 'W',  NULL, NULL, 'Ron Spears', 2, 1, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '5WW',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 2, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 0, 4, 'John Avon', 0, 3, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W',  NULL, NULL, 'Edward P. Beard, Jr.', 1, 4, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Rebecca Guay', 0, 5, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 2, 2, 'Mark Zug', 1, 6, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 2, 'Justin Sweet', 0, 7, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '4W', 2, 3, 'Greg & Tim Hildebrandt', 0, 8, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1WW',  NULL, NULL, 'Wayne England', 2, 9, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '2WW',  NULL, NULL, 'Scott M. Fischer', 2, 10, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 1, 'Darrell Riche', 1, 11, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 4, 'Terese Nielson', 1, 12, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', -1, -1, 'Daren Bader', 2, 13, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W',  NULL, NULL, 'Darrell Riche', 0, 14, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'John Avon', 0, 15, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Dave Dorman', 0, 16, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Luca Zontini', 2, 17, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 2, 'Clyde Caldwell', 2, 18, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1WW',  NULL, NULL, 'Ray Lago', 2, 19, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 1, 'rk post', 2, 20, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W',  NULL, NULL, 'Heather Hudson', 2, 21, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W',  NULL, NULL, 'Rebecca Guay', 0, 22, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W',  NULL, NULL, 'Mark Tedin', 1, 23, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 1, 4, 'Heather Hudson', 2, 24, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 1, 'Ben Thompson', 0, 25, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W',  NULL, NULL, 'Ray Lago', 2, 26, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', 'W',  NULL, NULL, 'Pete Venters', 0, 27, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '4WW',  NULL, NULL, 'Kev Walker', 2, 28, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 2, 'Paolo Parente', 2, 29, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W',  NULL, NULL, 'John Avon', 0, 30, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 4, 'Terese Nielson', 1, 31, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'WWW', 2, 2, 'Terese Nielson', 2, 32, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 1, 'Kev Walker', 2, 33, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Larry Elmore', 1, 34, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 2, 1, 'Matt Cavatto', 0, 35, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 4, 'Paolo Parente', 0, 36, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 2, 'Pete Venters', 1, 37, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 2, 2, 'Daren Bader', 0, 38, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 2, 'D. Alexander Gregory', 2, 39, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Orizio Daniele', 0, 40, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Massimilano Frezzato', 0, 41, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '3W',  NULL, NULL, 'Carl Critchlow', 0, 42, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 2, 3, 'Clyde Caldwell', 1, 43, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'W',  NULL, NULL, 'Bradley Williams', 0, 44, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '4W',  NULL, NULL, 'Ray Lago', 0, 45, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W',  NULL, NULL, 'Christopher Moeller', 0, 46, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 1, 'Ron Spencer', 1, 47, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 48, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 49, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 50, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 51, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 52, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W',  NULL, NULL, 'Christopher Moeller', 1, 53, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W',  NULL, NULL, 'Ben Thompson', 1, 54, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', 'W',  NULL, NULL, 'Roger Raupp', 1, 55, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Carl Critchlow', 0, 56, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '4WW', 4, 4, 'Mark Tedin', 2, 57, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4BB', 3, 3, 'Christopher Moeller', 2, 58, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', 'B',  NULL, NULL, 'Ciruelo', 0, 59, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Adam Rex', 0, 60, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '5BB', 6, 6, 'Heather Hudson', 2, 61, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Ray Lago', 1, 62, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'Christopher Moeller', 0, 63, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 2, 3, 'Kev Walker', 1, 64, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 3, 3, 'Greg & Tim Hildebrandt', 0, 65, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 1, 1, 'Ray Lago', 1, 66, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 3, 2, 'Wayne England', 1, 67, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '2B',  NULL, NULL, 'Alan Pollack', 1, 68, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '3BB',  NULL, NULL, 'Mark Brill', 2, 69, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'B',  NULL, NULL, 'Scott M. Fischer', 0, 70, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'Dave Dorman', 1, 71, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 1, 'Keith Garletts', 0, 72, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 2, 3, 'Tony Szczudlo', 2, 73, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Alan Pollack', 0, 74, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1BB',  NULL, NULL, 'Wayne England', 2, 75, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2BB',  NULL, NULL, 'Wayne England', 1, 76, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '6BB', -1, -1, 'Adam Rex', 2, 77, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '2BB',  NULL, NULL, 'Glen Angus & Arnie Swekel', 1, 78, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '4BB',  NULL, NULL, 'Daren Bader', 2, 79, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B',  NULL, NULL, 'Wayne England', 1, 80, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B',  NULL, NULL, 'Mike Ploog', 0, 81, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B',  NULL, NULL, 'Christopher Moeller', 2, 82, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 4, 3, 'Wayne England', 0, 83, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Scott M. Fischer', 0, 84, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'B',  NULL, NULL, 'Matt Cavatto', 2, 85, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3BB',  NULL, NULL, 'Scott M. Fischer', 1, 86, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Darrell Riche', 0, 87, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '4B',  NULL, NULL, 'Don Hazeltine', 1, 88, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', 'BBB', 2, 2, 'Donato Giancola', 2, 89, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', 'BB',  NULL, NULL, 'Heather Hudson', 2, 90, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B',  NULL, NULL, 'Adam Rex', 0, 91, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '3BB',  NULL, NULL, 'Adam Rex', 2, 92, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 2, 2, 'Wayne England', 0, 93, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Rebecca Guay', 1, 94, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Orizio Daniele', 0, 95, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 0, 1, 'Arnie Swekel', 1, 96, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 1, 2, 'Scott M. Fischer', 1, 97, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3B',  NULL, NULL, 'Terese Nielson', 0, 98, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Bradley Williams', 0, 99, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 2, 2, 'Kev Walker', 0, 100, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 1, 1, 'Greg Staples', 2, 101, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Heather Hudson', 1, 102, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'XB',  NULL, NULL, 'Pete Venters', 0, 103, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2B',  NULL, NULL, 'Jim Nelson', 1, 104, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 4, 4, 'Jim Nelson', 2, 105, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 2, 2, 'Luca Zontini', 1, 106, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', 'B', 1, 1, 'Arnie Swekel', 0, 107, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '8BB',  NULL, NULL, 'Paolo Parente', 2, 108, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B',  NULL, NULL, 'Eric Peterson', 0, 109, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3BB',  NULL, NULL, 'Greg Staples', 2, 110, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 2, 3, 'Carl Critchlow', 1, 111, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Ron Spencer', 2, 112, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '4BB',  NULL, NULL, 'Kev Walker', 2, 113, 1); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Eric Peterson', 0, 114, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '2N',  NULL, NULL, 'Roger Raupp', 0, 115, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Adam Rex', 2, 116, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 2, 'Eric Peterson', 2, 117, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N',  NULL, NULL, 'Greg Staples', 1, 118, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Alex Horley', 0, 119, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NNN', 5, 5, 'Mark Zug', 2, 120, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN',  NULL, NULL, 'Ben Thompson', 2, 121, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '4NN',  NULL, NULL, 'John Avon', 1, 122, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Larry Elmore', 1, 123, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'N',  NULL, NULL, 'Pete Venters', 0, 124, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 2, 1, 'John Matson', 0, 125, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 4, 3, 'Jeff Remmer', 2, 126, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN',  NULL, NULL, 'Don Hazeltine', 2, 127, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N',  NULL, NULL, 'Tony Szczudlo', 1, 128, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2NN',  NULL, NULL, 'Rick Farrell', 1, 129, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 3, 'Daren Bader', 0, 130, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 1, 'Edward P. Beard, Jr.', 0, 131, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'N',  NULL, NULL, 'Ron Spears', 2, 132, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '2N',  NULL, NULL, 'Gary Ruddell', 1, 133, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '5N', 3, 4, 'Thomas M. Baxa', 1, 134, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 3, 2, 'Adam Rex', 1, 135, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 2, 2, 'Adam Rex', 0, 136, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 2, 'John Matson', 0, 137, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Matt Cavatto', 0, 138, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'N',  NULL, NULL, 'Gary Ruddell', 0, 139, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Tony Szczudlo', 0, 140, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', 'NNN',  NULL, NULL, 'Alex Horley', 2, 141, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '3NN',  NULL, NULL, 'Arnie Swekel', 2, 142, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N',  NULL, NULL, 'Luca Zontini', 2, 143, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 1, 1, 'Anthony S. Waters', 1, 144, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N',  NULL, NULL, 'Carl Critchlow', 0, 145, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N',  NULL, NULL, 'Bradley Williams', 0, 146, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN',  NULL, NULL, 'Alex Horley', 1, 147, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N',  NULL, NULL, 'Marc Fishman', 0, 148, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 4, 3, 'Kev Walker', 2, 149, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '4NN',  NULL, NULL, 'Eric Peterson', 0, 150, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N',  NULL, NULL, 'Justin Sweet', 0, 151, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', -1, -1, 'Anthony S. Waters', 2, 152, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', 'NNNN',  NULL, NULL, 'Jerry Tiritilli', 2, 153, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 1, 2, 'Ray Lago', 0, 154, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 1, 1, 'Pete Venters', 1, 155, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '3N',  NULL, NULL, 'Eric Peterson', 0, 156, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 3, 3, 'Mark Tedin', 2, 157, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 3, 3, 'Kev Walker', 1, 158, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 2, 2, 'Paolo Parente', 1, 159, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '3NN',  NULL, NULL, 'Jerry Tiritilli', 1, 160, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'XN',  NULL, NULL, 'Bob Petillo', 1, 161, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N',  NULL, NULL, 'Paolo Parente', 1, 162, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4NN', 4, 4, 'Greg Staples', 2, 163, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N',  NULL, NULL, 'Adam Rex', 2, 164, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N',  NULL, NULL, 'Arnie Swekel', 2, 165, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '3NN',  NULL, NULL, 'Dave Dorman', 2, 166, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 1, 1, 'Daren Bader', 0, 167, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 3, 2, 'Pete Venters', 0, 168, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 1, 1, 'Adam Rex', 0, 169, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1N',  NULL, NULL, 'Thomas M. Baxa', 1, 170, 1); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '3N',  NULL, NULL, 'Mark Romanoski', 1, 171, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Mike Ploog', 0, 172, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 2, 2, 'Greg & Tim Hildebrandt', 0, 173, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '6RR', 6, 6, 'Mark Tedin', 2, 174, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 1, 'Ron Spears', 0, 175, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '3R',  NULL, NULL, 'Gary Ruddell', 1, 176, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1R',  NULL, NULL, 'Dave Dorman', 1, 177, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R',  NULL, NULL, 'rk post', 0, 178, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 1, 1, 'Greg & Tim Hildebrandt', 2, 179, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '3RR',  NULL, NULL, 'Ron Spencer', 2, 180, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Scott M. Fischer', 0, 181, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2RR',  NULL, NULL, 'Mark Brill', 2, 182, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Gary Ruddell', 1, 183, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '2R',  NULL, NULL, 'Greg & Tim Hildebrandt', 0, 184, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Mike Ploog', 0, 185, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 2, 'Ciruelo', 1, 186, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1RR',  NULL, NULL, 'Matt Cavatto', 2, 187, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 4, 3, 'Mike Ploog', 1, 188, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Wayne England', 0, 189, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 3, 4, 'Wayne England', 0, 190, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R',  NULL, NULL, 'Marc Fishman', 1, 191, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '4R',  NULL, NULL, 'Anthony S. Waters', 2, 192, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'R',  NULL, NULL, 'Ron Spencer', 0, 193, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R',  NULL, NULL, 'Ron Spencer', 0, 194, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 2, 3, 'Ron Spears', 1, 195, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 3, 1, 'Ben Thompson', 0, 196, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2RR',  NULL, NULL, 'Dave Dorman', 2, 197, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4RR', 6, 1, 'Kev Walker', 2, 198, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1R',  NULL, NULL, 'Dave Dorman', 0, 199, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Rob Alexander', 1, 200, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '4RR',  NULL, NULL, 'Greg Staples', 1, 201, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 2, 2, 'Ron Spencer', 0, 202, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R',  NULL, NULL, 'Glen Angus', 1, 203, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', -1, -1, 'Carl Critchlow', 2, 204, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 1, 1, 'Mark Brill', 2, 205, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 3, 3, 'Dave Dorman', 1, 206, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R',  NULL, NULL, 'Franz Vohwinkel', 2, 207, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '2R',  NULL, NULL, 'Gary Ruddell', 2, 208, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', 'R',  NULL, NULL, 'Christopher Moeller', 2, 209, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Terese Nielson', 2, 210, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 3, 'Glen Angus', 0, 211, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 1, 1, 'Tony Szczudlo', 2, 212, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 1, 1, 'Bob Petillo', 0, 213, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R',  NULL, NULL, 'Darrell Riche', 1, 214, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'R',  NULL, NULL, 'Scott M. Fischer', 0, 215, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Dave Dorman', 1, 216, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R',  NULL, NULL, 'Bradley Williams', 0, 217, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3RR', 0, 0, 'Dave Dorman', 2, 218, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Don Hazeltine', 0, 219, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Greg Staples', 2, 220, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3RR',  NULL, NULL, 'Matt Cavatto', 1, 221, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Paolo Parente', 1, 222, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1RR',  NULL, NULL, 'Anthony S. Waters', 1, 223, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '4R',  NULL, NULL, 'Franz Vohwinkel', 0, 224, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Ciruelo', 0, 225, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Matt Cavatto', 1, 226, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '8R',  NULL, NULL, 'Tony Szczudlo', 2, 227, 1); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 1, 1, 'Ron Spencer', 1, 228, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Heather Hudson', 2, 229, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2VVV',  NULL, NULL, 'Ciruelo', 1, 230, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2V',  NULL, NULL, 'Carl Critchlow', 2, 231, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 2, 'Donato Giancola', 0, 232, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V',  NULL, NULL, 'Jim Nelson', 0, 233, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'VVV', 1, 1, 'John Avon', 2, 234, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4VV', 3, 4, 'Eric Peterson', 1, 235, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2V',  NULL, NULL, 'Jeff Remmer', 1, 236, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Gary Ruddell', 0, 237, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Mark Zug', 0, 238, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1V',  NULL, NULL, 'Greg & Tim Hildebrandt', 1, 239, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2VV',  NULL, NULL, 'Anthony S. Waters', 0, 240, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 4, 4, 'Heather Hudson', 1, 241, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1V',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 242, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Rebecca Guay', 2, 243, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Greg Staples', 1, 244, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'XV', 0, 0, 'Ron Spencer', 2, 245, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 3, 'Ron Spears', 0, 246, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 3, 1, 'D. Alexander Gregory', 0, 247, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 1, 1, 'Kev Walker', 2, 248, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', 2, 2, 'Greg & Tim Hildebrandt', 0, 249, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 3, 3, 'Thomas M. Baxa', 1, 250, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Rebecca Guay', 0, 251, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Gary Ruddell', 0, 252, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Justin Sweet', 0, 253, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 2, 'Daren Bader', 1, 254, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 1, 'John Matson', 2, 255, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Rebecca Guay', 2, 256, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'XV',  NULL, NULL, 'Ron Spencer', 2, 257, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Terese Nielson', 1, 258, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5V', 1, 1, 'Christopher Moeller', 2, 259, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2VVV',  NULL, NULL, 'Carl Critchlow', 1, 260, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V',  NULL, NULL, 'Greg & Tim Hildebrandt', 1, 261, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', 'V',  NULL, NULL, 'Alex Horley', 0, 262, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4V', 3, 4, 'Dave Dorman', 0, 263, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2V',  NULL, NULL, 'Keith Garletts', 0, 264, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '1V',  NULL, NULL, 'Bradley Williams', 0, 265, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '6V',  NULL, NULL, 'Kev Walker', 1, 266, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'VVV', 2, 2, 'Greg Staples', 2, 267, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2V',  NULL, NULL, 'Ciruelo', 0, 268, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V',  NULL, NULL, 'Greg & Tim Hildebrandt', 0, 269, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 2, 'Jerry Tiritilli', 1, 270, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 3, 2, 'Rick Farrell', 2, 271, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 3, 3, 'Arnie Swekel', 0, 272, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', 2, 2, 'Carl Critchlow', 2, 273, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Anthony S. Waters', 1, 274, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Matt Cavatto', 1, 275, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4VVV', 4, 5, 'Wayne England', 2, 276, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Arnie Swekel', 1, 277, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', -1, -1, 'Jim Nelson', 2, 278, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 2, 'Carl Critchlow', 1, 279, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '4V',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 280, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2V',  NULL, NULL, 'Greg Staples', 1, 281, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 1, 'Carl Critchlow', 0, 282, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 2, 'Anthony S. Waters', 0, 283, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 2, 'Rick Farrell', 0, 284, 1); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 1, 2, 'Alex Horley', 2, 285, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', 'WBNRV', 5, 5, 'Ron Spears', 2, 286, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'rituel', '2RV',  NULL, NULL, 'Alex Horley', 2, 287, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '5WB', 4, 4, 'Matt Cavatto', 2, 288, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1RV', 1, 2, 'Franz Vohwinkel', 1, 289, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '2VW', 3, 3, 'Gary Ruddell', 2, 290, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1WB', 1, 2, 'Glen Angus', 1, 291, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1BN', 1, 2, 'Edward P. Beard, Jr.', 1, 292, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1NR', 1, 2, 'Mark Brill', 1, 293, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1BN', 1, 3, 'Rick Farrell', 2, 294, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1VW', 1, 2, 'Monte Michael Moore', 1, 295, 1); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '6NR', 5, 5, 'Gary Ruddell', 2, 296, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '2',  NULL, NULL, 'Tony Szczudlo', 2, 297, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4',  NULL, NULL, 'Anthony S. Waters', 2, 298, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 299, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4', 0, 0, 'Brian Snoddy', 2, 300, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '6', 3, 4, 'Mark Tedin', 1, 301, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '2', 0, 1, 'Alex Horley', 1, 302, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'creature', '5',  NULL, NULL, 'Donato Giancola', 2, 303, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 304, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4', 2, 3, 'Brian Snoddy', 2, 305, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '3', 2, 1, 'Jerry Tiritilli', 1, 306, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '3',  NULL, NULL, 'Jim Nelson', 1, 307, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4',  NULL, NULL, 'David Martin', 1, 308, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 309, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '2',  NULL, NULL, 'Jim Nelson', 1, 310, 1); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 311, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Edward P. Beard, Jr.', 0, 312, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 313, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Brian Snoddy', 0, 314, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 315, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 316, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 317, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 2, 318, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Monte Michael Moore', 2, 319, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 2, 320, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 2, 321, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 1, 322, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Glen Angus', 2, 323, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 0, 324, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 325, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Glen Angus', 2, 326, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 2, 327, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Ron Spencer', 2, 328, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 2, 329, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 330, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 331, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Don Hazeltine', 0, 332, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Eric Peterson', 0, 333, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 334, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 335, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Ben Thompson', 0, 336, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 337, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 338, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Jerry Tiritilli', 0, 339, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Arnie Swekel', 0, 340, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 341, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 342, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Anthony S. Waters', 0, 343, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Franz Vohwinkel', 0, 344, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 345, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Tony Szczudlo', 0, 346, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 347, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 348, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Jerry Tiritilli', 0, 349, 1); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Tony Szczudlo', 0, 350, 1); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '6W', 5, 5, 'rk post', 2, 1, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 1, 'Greg Staples', 0, 2, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '1WW', NULL, NULL, 'Ron Spears', 1, 3, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Greg & Tim Hildebrandt', 1, 4, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Keith Garletts', 0, 5, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W', NULL, NULL, 'Mark Brill', 0, 6, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Christopher Moeller', 1, 7, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 3, 'Daren Bader', 2, 8, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 1, 'Mark Brill', 0, 9, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '1W', NULL, NULL, 'Tony Szczudlo', 2, 10, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 2, 'Edward P. Beard, Jr.', 0, 11, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'W', NULL, NULL, 'Adam Rex', 0, 12, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 3, 3, 'Eric Peterson', 2, 13, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Gary Ruddell', 2, 14, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '3W', NULL, NULL, 'rk post', 0, 15, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Matt Cavotta', 1, 16, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Jerry Tiritilli', 1, 17, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 4, 'Greg & Tim Hildebrandt', 0, 18, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 3, 'Greg & Tim Hildebrandt', 1, 19, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3WWW', NULL, NULL, 'Rebecca Guay', 2, 20, 2); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'WW', NULL, NULL, 'Mark Tedin', 2, 21, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Justin Sweet', 2, 22, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1BB', 1, 3, 'Eric Peterson', 2, 23, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 3, 'Arnie Swekel', 0, 24, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'DiTerlizzi', 1, 25, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'XB', NULL, NULL, 'Gary Ruddell', 1, 26, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 3, 3, 'Rob Alexander', 0, 27, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Pete Venters', 1, 28, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 3, 'Keith Garletts', 1, 29, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Jerry Tiritilli', 0, 30, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Alex Horley', 2, 31, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B', NULL, NULL, 'Thomas M. Baxa', 0, 32, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Anthony S. Waters', 1, 33, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'Christopher Moeller', 1, 34, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', 'B', NULL, NULL, 'Roger Raupp', 0, 35, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B', NULL, NULL, 'Daren Bader', 0, 36, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Ron Spencer', 2, 37, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'David Martin', 0, 38, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 2, 'Glen Angus', 0, 39, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 3, 3, 'Arnie Swekel', 1, 40, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Ron Spencer', 0, 41, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 3, 'Mark Zug', 2, 42, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Jim Nelson', 0, 43, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3B', NULL, NULL, 'Ben Thompson', 2, 44, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 3, 3, 'Scott M. Fischer', 2, 45, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'B', NULL, NULL, 'Greg Staples', 2, 46, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 1, 'Matt Cavotta', 0, 47, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'Bradley Williams', 1, 48, 2); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'BB', NULL, NULL, 'Wayne England', 2, 49, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Ron Spencer', 1, 50, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N', NULL, NULL, 'Greg & Tim Hildebrandt', 0, 51, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 1, 'Donato Giancola', 0, 52, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1NN', 1, 1, 'Pete Venters', 0, 53, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 2, 1, 'Edward P. Beard, Jr.', 0, 54, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 6, 5, 'Glen Angus', 1, 55, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 3, 3, 'Mark Zug', 2, 56, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N', NULL, NULL, 'Ben Thompson', 1, 57, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1NN', NULL, NULL, 'Heather Hudson', 0, 58, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '2NNN', NULL, NULL, 'Pete Venters', 2, 59, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 3, 'Daren Bader', 0, 60, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Adam Rex', 1, 61, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 2, 'Daren Bader', 0, 62, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 3, 3, 'Terese Nielsen', 1, 63, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '8NNN', 8, 8, 'Greg Staples', 2, 64, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 3, 1, 'rk post', 2, 65, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '3N', NULL, NULL, 'John Avon', 2, 66, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4NN', 6, 3, 'Greg Staples', 2, 67, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '2NN', NULL, NULL, 'John Matson', 2, 68, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Dana Knutson', 0, 69, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '4N', NULL, NULL, 'Eric Peterson', 1, 70, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '2NN', NULL, NULL, 'Mike Ploog', 2, 71, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN', NULL, NULL, 'Christopher Moeller', 1, 72, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2NN', NULL, NULL, 'Eric Peterson', 2, 73, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'NN', 2, 1, 'Brian Snoddy', 2, 74, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 3, 1, 'Adam Rex', 0, 75, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '2NN', NULL, NULL, 'Alex Horley', 0, 76, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 1, 1, 'Wayne England', 0, 77, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1NN', NULL, NULL, 'Ciruelo', 0, 78, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N', NULL, NULL, 'John Matson', 0, 79, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 4, 4, 'Kev Walker', 2, 80, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN', NULL, NULL, 'Clyde Caldwell', 0, 81, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1NNN', 3, 3, 'Arnie Swekel', 2, 82, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N', NULL, NULL, 'Scott M. Fischer', 1, 83, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1NN', 1, 1, 'John Avon', 1, 84, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 3, 2, 'Carl Critchlow', 0, 85, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1N', NULL, NULL, 'Greg & Tim Hildebrandt', 1, 86, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N', NULL, NULL, 'Keith Garletts', 0, 87, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '4N', NULL, NULL, 'Alan Pollack', 0, 88, 2); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'NNN', 2, 2, 'Brian Snoddy', 1, 89, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R', NULL, NULL, 'Gary Ruddell', 0, 90, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1RR', 2, 2, 'Ron Spears', 2, 91, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 2, 2, 'Mark Tedin', 0, 92, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', 'R', NULL, NULL, 'Mike Ploog', 0, 93, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '5RR', 4, 4, 'Ron Spears', 1, 94, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'RR', NULL, NULL, 'Tony Szczudlo', 2, 95, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Terese Nielsen', 0, 96, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1RR', NULL, NULL, 'Greg & Tim Hildebrandt', 0, 97, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'XR', NULL, NULL, 'Donato Giancola', 1, 98, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R', NULL, NULL, 'Carl Critchlow', 0, 99, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Jim Nelson', 2, 100, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1RR', 2, 2, 'Mike Ploog', 2, 101, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '5RR', NULL, NULL, 'Don Hazeltine', 0, 102, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 3, 2, 'Glen Angus', 0, 103, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'R', NULL, NULL, 'Anthony S. Waters', 2, 104, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 3, 3, 'rk post', 1, 105, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Pete Venters', 1, 106, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 3, 2, 'Justin Sweet', 0, 107, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '6RR', 5, 6, 'Jim Nelson', 2, 108, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Wayne England', 0, 109, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 5, 'David Martin', 1, 110, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 3, 3, 'Scott M. Fischer', 2, 111, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R', NULL, NULL, 'Christopher Moeller', 1, 112, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '3RR', NULL, NULL, 'Carl Critchlow', 2, 113, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'RR', NULL, NULL, 'Bradley Williams', 2, 114, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R', NULL, NULL, 'Terese Nielsen', 0, 115, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '3R', NULL, NULL, 'Mark Romanoski', 1, 116, 2); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1RRR', NULL, NULL, 'Bob Petillo', 1, 117, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '3V', NULL, NULL, 'Edward P. Beard, Jr.', 0, 118, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 3, 3, 'Bob Petillo', 1, 119, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 4, 4, 'John Avon', 1, 120, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Heather Hudson', 0, 121, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 3, 3, 'Justin Sweet', 1, 122, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5V', 3, 3, 'Mark Zug', 0, 123, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V', NULL, NULL, 'Rebecca Guay', 1, 124, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2V', NULL, NULL, 'Darrell Riche', 0, 125, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 6, 8, 'Scott M. Fischer', 2, 126, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V', NULL, NULL, 'Franz Vohwinkel', 2, 127, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2VV', NULL, NULL, 'Rebecca Guay', 0, 128, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Jim Nelson', 0, 129, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 2, 'Clyde Caldwell', 0, 130, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 2, 'Matt Cavotta', 2, 131, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2VV', 2, 3, 'Mark Romanoski', 0, 132, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Darrell Riche', 2, 133, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2V', NULL, NULL, 'Christopher Moeller', 1, 134, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'VV', NULL, NULL, 'Darrell Riche', 2, 135, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '3VV', NULL, NULL, 'Matt Cavotta', 2, 136, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2VV', 3, 3, 'Alex Horley', 2, 137, 2); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 1, 'Mark Romanoski', 1, 138, 2); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 139, 2); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 140, 2); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Alan Pollack', 1, 141, 2); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Tony Szczudlo', 1, 142, 2); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Rob Alexander', 1, 143, 2);
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '5WW', 4, 4, 'Pete Venters', 1, 1, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W', NULL, NULL, 'Roger Raupp', 1, 2, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '2WW', NULL, NULL, 'Randy Gallegos', 1, 3, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 2, 'Wayne England', 0, 4, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Roger Raupp', 0, 5, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '4W', 1, 6, 'Roger Raupp', 0, 6, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Scott M. Fischer', 0, 7, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '3W', NULL, NULL, 'Carl Critchlow', 1, 8, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 2, 4, 'Rebecca Guay', 2, 9, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'W', NULL, NULL, 'Carl Critchlow', 0, 10, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 3, 3, 'Donato Giancola', 2, 11, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '3WW', NULL, NULL, 'Alan Pollack', 2, 12, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Dave Dorman', 0, 13, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Adam Rex', 0, 14, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Eric Peterson', 2, 15, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 0, 0, 'David Martin', 1, 16, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 0, 0, 'Jim Nelson', 0, 17, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W', NULL, NULL, 'Eric Peterson', 0, 18, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Jeff Easley', 2, 19, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Doug Chaffee', 0, 20, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 3, 4, 'Christopher Moeller', 2, 21, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Christopher Moeller', 0, 22, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '5WWW', 6, 6, 'Matthew D. Wilson', 2, 23, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Scott M. Fischer', 2, 24, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Rob Alexander', 1, 25, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Gary Ruddell', 1, 26, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Ron Spears', 1, 27, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Heather Hudson', 0, 28, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2WW', NULL, NULL, 'Mike Ploog', 2, 29, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 1, 'John Matson', 0, 30, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Alex Horley', 1, 31, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 2, 'Kev Walker', 1, 32, 3); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 2, 'Eric Peterson', 0, 33, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 1, 'Edward P. Beard, Jr.', 0, 34, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1BB', 1, 1, 'Alan Pollack', 2, 35, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 1, 'Tony Szczudlo', 1, 36, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Jim Nelson', 2, 37, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Ben Thompson', 0, 38, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Don Hazeltine', 0, 39, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'X1B', NULL, NULL, 'Ben Thompson', 1, 40, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Bradley Williams', 0, 41, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', 'B', 1, 1, 'Ron Spears', 0, 42, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Fred Rahmqvist', 0, 43, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Pete Venters', 1, 44, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'Ben Thompson', 0, 45, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Bradley Williams', 0, 46, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 3, 4, 'Mark Brill', 0, 47, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '3BB', NULL, NULL, 'Mike Ploog', 2, 48, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '1B', NULL, NULL, 'John Avon', 1, 49, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 1, 5, 'Mark Tedin', 2, 50, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3BBB', NULL, NULL, 'Pete Venters', 2, 51, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2BBB', NULL, NULL, 'Jim Nelson', 2, 52, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2B', NULL, NULL, 'Don Hazeltine', 1, 53, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'Rebecca Guay', 1, 54, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 5, 5, 'Heather Hudson', 2, 55, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 3, 6, 'Glen Angus', 1, 56, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 3, 4, 'Thomas M. Baxa', 0, 57, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '5BB', 6, 1, 'Heather Hudson', 2, 58, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 2, 2, 'Doug Chaffee', 0, 59, 3); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 4, 'John Avon', 1, 60, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 2, 'Carl Critchlow', 2, 61, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N', NULL, NULL, 'Ron Spencer', 1, 62, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 1, 1, 'Pete Venters', 0, 63, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1NN', NULL, NULL, 'Jeff Easley', 2, 64, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 1, 'Heather Hudson', 0, 65, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Thomas M. Baxa', 1, 66, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N', NULL, NULL, 'Tim Hildebrandt', 1, 67, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 0, 4, 'Mark Tedin', 2, 68, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 5, 5, 'Matthew D. Wilson', 2, 69, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '5NN', NULL, NULL, 'Jerry Tiritilli', 2, 70, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'XN', NULL, NULL, 'Bob Petillo', 0, 71, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'NN', NULL, NULL, 'Arnie Swekel', 1, 72, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4NNN', -1, -1, 'Carl Critchlow', 2, 73, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N', NULL, NULL, 'Bradley Williams', 0, 74, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 4, 4, 'Kev Walker', 1, 75, 3); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 2, 'Mark Tedin', 0, 76, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'John Avon', 1, 77, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R', NULL, NULL, 'Mark Brill', 0, 78, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 2, 'Mike Ploog', 0, 79, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R', NULL, NULL, 'Dave Dorman', 0, 80, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1RR', NULL, NULL, 'Matthew D. Wilson', 2, 81, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '2R', NULL, NULL, 'Mark Tedin', 1, 82, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R', NULL, NULL, 'Scott M. Fischer', 2, 83, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'RRR', 2, 2, 'Arnie Swekel', 2, 84, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Edward P. Beard, Jr.', 1, 85, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Thomas M. Baxa', 0, 86, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '6R', NULL, NULL, 'Alan Pollack', 0, 87, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'XRR', NULL, NULL, 'David Martin', 1, 88, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R', NULL, NULL, 'Glen Angus', 0, 89, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 2, 2, 'Greg Staples', 2, 90, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '5R', 2, 2, 'Keith Garletts', 0, 91, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1R', NULL, NULL, 'Christopher Moeller', 1, 92, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 3, 1, 'rk post', 2, 93, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R', NULL, NULL, 'Darrell Riche', 0, 94, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Greg Hildebrandt', 0, 95, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3RR', NULL, NULL, 'Ron Spears', 2, 96, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R', NULL, NULL, 'Ron Spencer', 1, 97, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '2R', NULL, NULL, 'Greg Hildebrandt', 2, 98, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3RR', 6, 6, 'John Matson', 1, 99, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 3, 1, 'Mark Romanoski', 0, 100, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R', NULL, NULL, 'Ben Thompson', 1, 101, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R', NULL, NULL, 'Tony Szczudlo', 0, 102, 3); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3RRR', 7, 7, 'Wayne England', 2, 103, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', 2, 2, 'Randy Gallegos', 0, 104, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 4, 'John Matson', 1, 105, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 3, 3, 'Daren Bader', 0, 106, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 3, 3, 'Matt Cavotta', 1, 107, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', 'V', NULL, NULL, 'Matthew Mitchell', 0, 108, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Eric Peterson', 0, 109, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '6VVV', NULL, NULL, 'Christopher Moeller', 2, 110, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2V', NULL, NULL, 'Jim Nelson', 1, 111, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2VV', NULL, NULL, 'Greg & Tim Hildebrandt', 2, 112, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 4, 5, 'Greg Staples', 2, 113, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1V', NULL, NULL, 'Wayne England', 1, 114, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2V', NULL, NULL, 'Matt Cavotta', 0, 115, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 1, 'Darrell Riche', 1, 116, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4V', 4, 4, 'Mark Zug', 2, 117, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5V', 5, 5, 'Kev Walker', 0, 118, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '3VV', NULL, NULL, 'Dave Dorman', 1, 119, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 1, 'David Martin', 0, 120, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 1, 'Heather Hudson', 0, 121, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V', NULL, NULL, 'Gary Ruddell', 1, 122, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Edward P. Beard, Jr.', 0, 123, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '1V', NULL, NULL, 'Eric Peterson', 2, 124, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 1, 'Greg Staples', 0, 125, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 3, 'Darrell Riche', 0, 126, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2VV', 2, 0, 'Carl Critchlow', 1, 127, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 0, 0, 'Wayne England', 2, 128, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 0, 'Brian Snoddy', 0, 129, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V', NULL, NULL, 'Rebecca Guay', 2, 130, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', 'XV', NULL, NULL, 'David Martin', 1, 131, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '3V', NULL, NULL, 'Alan Pollack', 0, 132, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Pete Venters', 2, 133, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5VV', 5, 5, 'John Avon', 2, 134, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '6VV', 6, 6, 'Jeff Easley', 1, 135, 3); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2VV', NULL, NULL, 'Ron Spencer', 0, 136, 3); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1VW', 3, 4, 'Arnie Swekel', 2, 137, 3); 
INSERT INTO carte_virtuelle VALUES ('M', 'enchantement', 'VW', NULL, NULL, 'Mark Brill', 2, 138, 3); 
INSERT INTO carte_virtuelle VALUES ('M', 'enchantement', '3VW', NULL, NULL, 'David Martin', 2, 139, 3); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '5VW', 0, 0, 'Arnie Swekel', 2, 140, 3); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Tony Szczudlo', 1, 141, 3); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Rob Alexander', 1, 142, 3); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 143, 3);  

