INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', 'W',  NULL, NULL, 'Ron Spears', 2, 1, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '5WW',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 2, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 0, 4, 'John Avon', 0, 3, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W',  NULL, NULL, 'Edward P. Beard, Jr.', 1, 4, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Rebecca Guay', 0, 5, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 2, 2, 'Mark Zug', 1, 6, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 2, 'Justin Sweet', 0, 7, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '4W', 2, 3, 'Greg & Tim Hildebrandt', 0, 8, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1WW',  NULL, NULL, 'Wayne England', 2, 9, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '2WW',  NULL, NULL, 'Scott M. Fischer', 2, 10, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 1, 'Darrell Riche', 1, 11, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 4, 'Terese Nielson', 1, 12, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', -1, -1, 'Daren Bader', 2, 13, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W',  NULL, NULL, 'Darrell Riche', 0, 14, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'John Avon', 0, 15, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Dave Dorman', 0, 16, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Luca Zontini', 2, 17, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 2, 'Clyde Caldwell', 2, 18, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1WW',  NULL, NULL, 'Ray Lago', 2, 19, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 1, 'rk post', 2, 20, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W',  NULL, NULL, 'Heather Hudson', 2, 21, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W',  NULL, NULL, 'Rebecca Guay', 0, 22, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W',  NULL, NULL, 'Mark Tedin', 1, 23, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 1, 4, 'Heather Hudson', 2, 24, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 1, 'Ben Thompson', 0, 25, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W',  NULL, NULL, 'Ray Lago', 2, 26, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', 'W',  NULL, NULL, 'Pete Venters', 0, 27, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '4WW',  NULL, NULL, 'Kev Walker', 2, 28, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 2, 'Paolo Parente', 2, 29, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W',  NULL, NULL, 'John Avon', 0, 30, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 4, 'Terese Nielson', 1, 31, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'WWW', 2, 2, 'Terese Nielson', 2, 32, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 1, 'Kev Walker', 2, 33, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Larry Elmore', 1, 34, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 2, 1, 'Matt Cavatto', 0, 35, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 4, 'Paolo Parente', 0, 36, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 2, 'Pete Venters', 1, 37, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 2, 2, 'Daren Bader', 0, 38, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 2, 'D. Alexander Gregory', 2, 39, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Orizio Daniele', 0, 40, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Massimilano Frezzato', 0, 41, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '3W',  NULL, NULL, 'Carl Critchlow', 0, 42, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 2, 3, 'Clyde Caldwell', 1, 43, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'W',  NULL, NULL, 'Bradley Williams', 0, 44, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '4W',  NULL, NULL, 'Ray Lago', 0, 45, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W',  NULL, NULL, 'Christopher Moeller', 0, 46, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 1, 'Ron Spencer', 1, 47, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 48, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 49, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 50, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 51, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 52, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W',  NULL, NULL, 'Christopher Moeller', 1, 53, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W',  NULL, NULL, 'Ben Thompson', 1, 54, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', 'W',  NULL, NULL, 'Roger Raupp', 1, 55, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Carl Critchlow', 0, 56, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '4WW', 4, 4, 'Mark Tedin', 2, 57, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4BB', 3, 3, 'Christopher Moeller', 2, 58, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', 'B',  NULL, NULL, 'Ciruelo', 0, 59, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Adam Rex', 0, 60, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '5BB', 6, 6, 'Heather Hudson', 2, 61, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Ray Lago', 1, 62, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'Christopher Moeller', 0, 63, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 2, 3, 'Kev Walker', 1, 64, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 3, 3, 'Greg & Tim Hildebrandt', 0, 65, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 1, 1, 'Ray Lago', 1, 66, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 3, 2, 'Wayne England', 1, 67, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '2B',  NULL, NULL, 'Alan Pollack', 1, 68, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '3BB',  NULL, NULL, 'Mark Brill', 2, 69, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'B',  NULL, NULL, 'Scott M. Fischer', 0, 70, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'Dave Dorman', 1, 71, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 1, 'Keith Garletts', 0, 72, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 2, 3, 'Tony Szczudlo', 2, 73, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Alan Pollack', 0, 74, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1BB',  NULL, NULL, 'Wayne England', 2, 75, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2BB',  NULL, NULL, 'Wayne England', 1, 76, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '6BB', -1, -1, 'Adam Rex', 2, 77, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '2BB',  NULL, NULL, 'Glen Angus & Arnie Swekel', 1, 78, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '4BB',  NULL, NULL, 'Daren Bader', 2, 79, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B',  NULL, NULL, 'Wayne England', 1, 80, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B',  NULL, NULL, 'Mike Ploog', 0, 81, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B',  NULL, NULL, 'Christopher Moeller', 2, 82, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 4, 3, 'Wayne England', 0, 83, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Scott M. Fischer', 0, 84, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'B',  NULL, NULL, 'Matt Cavatto', 2, 85, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3BB',  NULL, NULL, 'Scott M. Fischer', 1, 86, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Darrell Riche', 0, 87, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '4B',  NULL, NULL, 'Don Hazeltine', 1, 88, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', 'BBB', 2, 2, 'Donato Giancola', 2, 89, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', 'BB',  NULL, NULL, 'Heather Hudson', 2, 90, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B',  NULL, NULL, 'Adam Rex', 0, 91, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '3BB',  NULL, NULL, 'Adam Rex', 2, 92, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 2, 2, 'Wayne England', 0, 93, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Rebecca Guay', 1, 94, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Orizio Daniele', 0, 95, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 0, 1, 'Arnie Swekel', 1, 96, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 1, 2, 'Scott M. Fischer', 1, 97, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3B',  NULL, NULL, 'Terese Nielson', 0, 98, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Bradley Williams', 0, 99, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 2, 2, 'Kev Walker', 0, 100, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 1, 1, 'Greg Staples', 2, 101, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Heather Hudson', 1, 102, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'XB',  NULL, NULL, 'Pete Venters', 0, 103, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2B',  NULL, NULL, 'Jim Nelson', 1, 104, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 4, 4, 'Jim Nelson', 2, 105, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 2, 2, 'Luca Zontini', 1, 106, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', 'B', 1, 1, 'Arnie Swekel', 0, 107, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '8BB',  NULL, NULL, 'Paolo Parente', 2, 108, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B',  NULL, NULL, 'Eric Peterson', 0, 109, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3BB',  NULL, NULL, 'Greg Staples', 2, 110, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 2, 3, 'Carl Critchlow', 1, 111, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B',  NULL, NULL, 'Ron Spencer', 2, 112, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '4BB',  NULL, NULL, 'Kev Walker', 2, 113, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B',  NULL, NULL, 'Eric Peterson', 0, 114, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '2N',  NULL, NULL, 'Roger Raupp', 0, 115, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Adam Rex', 2, 116, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 2, 'Eric Peterson', 2, 117, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N',  NULL, NULL, 'Greg Staples', 1, 118, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Alex Horley', 0, 119, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NNN', 5, 5, 'Mark Zug', 2, 120, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN',  NULL, NULL, 'Ben Thompson', 2, 121, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '4NN',  NULL, NULL, 'John Avon', 1, 122, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Larry Elmore', 1, 123, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'N',  NULL, NULL, 'Pete Venters', 0, 124, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 2, 1, 'John Matson', 0, 125, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 4, 3, 'Jeff Remmer', 2, 126, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN',  NULL, NULL, 'Don Hazeltine', 2, 127, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N',  NULL, NULL, 'Tony Szczudlo', 1, 128, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2NN',  NULL, NULL, 'Rick Farrell', 1, 129, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 3, 'Daren Bader', 0, 130, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 1, 'Edward P. Beard, Jr.', 0, 131, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'N',  NULL, NULL, 'Ron Spears', 2, 132, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '2N',  NULL, NULL, 'Gary Ruddell', 1, 133, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '5N', 3, 4, 'Thomas M. Baxa', 1, 134, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 3, 2, 'Adam Rex', 1, 135, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 2, 2, 'Adam Rex', 0, 136, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 2, 'John Matson', 0, 137, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Matt Cavatto', 0, 138, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'N',  NULL, NULL, 'Gary Ruddell', 0, 139, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Tony Szczudlo', 0, 140, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', 'NNN',  NULL, NULL, 'Alex Horley', 2, 141, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '3NN',  NULL, NULL, 'Arnie Swekel', 2, 142, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N',  NULL, NULL, 'Luca Zontini', 2, 143, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 1, 1, 'Anthony S. Waters', 1, 144, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N',  NULL, NULL, 'Carl Critchlow', 0, 145, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N',  NULL, NULL, 'Bradley Williams', 0, 146, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN',  NULL, NULL, 'Alex Horley', 1, 147, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N',  NULL, NULL, 'Marc Fishman', 0, 148, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 4, 3, 'Kev Walker', 2, 149, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '4NN',  NULL, NULL, 'Eric Peterson', 0, 150, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N',  NULL, NULL, 'Justin Sweet', 0, 151, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', -1, -1, 'Anthony S. Waters', 2, 152, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', 'NNNN',  NULL, NULL, 'Jerry Tiritilli', 2, 153, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 1, 2, 'Ray Lago', 0, 154, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 1, 1, 'Pete Venters', 1, 155, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '3N',  NULL, NULL, 'Eric Peterson', 0, 156, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 3, 3, 'Mark Tedin', 2, 157, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 3, 3, 'Kev Walker', 1, 158, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 2, 2, 'Paolo Parente', 1, 159, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '3NN',  NULL, NULL, 'Jerry Tiritilli', 1, 160, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', 'XN',  NULL, NULL, 'Bob Petillo', 1, 161, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N',  NULL, NULL, 'Paolo Parente', 1, 162, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4NN', 4, 4, 'Greg Staples', 2, 163, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N',  NULL, NULL, 'Adam Rex', 2, 164, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N',  NULL, NULL, 'Arnie Swekel', 2, 165, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '3NN',  NULL, NULL, 'Dave Dorman', 2, 166, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 1, 1, 'Daren Bader', 0, 167, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 3, 2, 'Pete Venters', 0, 168, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 1, 1, 'Adam Rex', 0, 169, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1N',  NULL, NULL, 'Thomas M. Baxa', 1, 170, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '3N',  NULL, NULL, 'Mark Romanoski', 1, 171, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Mike Ploog', 0, 172, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 2, 2, 'Greg & Tim Hildebrandt', 0, 173, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '6RR', 6, 6, 'Mark Tedin', 2, 174, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 1, 'Ron Spears', 0, 175, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '3R',  NULL, NULL, 'Gary Ruddell', 1, 176, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1R',  NULL, NULL, 'Dave Dorman', 1, 177, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R',  NULL, NULL, 'rk post', 0, 178, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 1, 1, 'Greg & Tim Hildebrandt', 2, 179, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '3RR',  NULL, NULL, 'Ron Spencer', 2, 180, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Scott M. Fischer', 0, 181, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2RR',  NULL, NULL, 'Mark Brill', 2, 182, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Gary Ruddell', 1, 183, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '2R',  NULL, NULL, 'Greg & Tim Hildebrandt', 0, 184, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Mike Ploog', 0, 185, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 2, 'Ciruelo', 1, 186, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1RR',  NULL, NULL, 'Matt Cavatto', 2, 187, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 4, 3, 'Mike Ploog', 1, 188, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Wayne England', 0, 189, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 3, 4, 'Wayne England', 0, 190, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R',  NULL, NULL, 'Marc Fishman', 1, 191, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '4R',  NULL, NULL, 'Anthony S. Waters', 2, 192, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'R',  NULL, NULL, 'Ron Spencer', 0, 193, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R',  NULL, NULL, 'Ron Spencer', 0, 194, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 2, 3, 'Ron Spears', 1, 195, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 3, 1, 'Ben Thompson', 0, 196, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2RR',  NULL, NULL, 'Dave Dorman', 2, 197, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4RR', 6, 1, 'Kev Walker', 2, 198, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1R',  NULL, NULL, 'Dave Dorman', 0, 199, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Rob Alexander', 1, 200, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '4RR',  NULL, NULL, 'Greg Staples', 1, 201, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 2, 2, 'Ron Spencer', 0, 202, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R',  NULL, NULL, 'Glen Angus', 1, 203, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', -1, -1, 'Carl Critchlow', 2, 204, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 1, 1, 'Mark Brill', 2, 205, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 3, 3, 'Dave Dorman', 1, 206, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R',  NULL, NULL, 'Franz Vohwinkel', 2, 207, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '2R',  NULL, NULL, 'Gary Ruddell', 2, 208, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', 'R',  NULL, NULL, 'Christopher Moeller', 2, 209, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Terese Nielson', 2, 210, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 3, 'Glen Angus', 0, 211, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 1, 1, 'Tony Szczudlo', 2, 212, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 1, 1, 'Bob Petillo', 0, 213, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R',  NULL, NULL, 'Darrell Riche', 1, 214, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'R',  NULL, NULL, 'Scott M. Fischer', 0, 215, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Dave Dorman', 1, 216, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R',  NULL, NULL, 'Bradley Williams', 0, 217, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3RR', 0, 0, 'Dave Dorman', 2, 218, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Don Hazeltine', 0, 219, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R',  NULL, NULL, 'Greg Staples', 2, 220, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3RR',  NULL, NULL, 'Matt Cavatto', 1, 221, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Paolo Parente', 1, 222, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1RR',  NULL, NULL, 'Anthony S. Waters', 1, 223, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '4R',  NULL, NULL, 'Franz Vohwinkel', 0, 224, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Ciruelo', 0, 225, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R',  NULL, NULL, 'Matt Cavatto', 1, 226, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '8R',  NULL, NULL, 'Tony Szczudlo', 2, 227, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 1, 1, 'Ron Spencer', 1, 228, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Heather Hudson', 2, 229, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2VVV',  NULL, NULL, 'Ciruelo', 1, 230, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2V',  NULL, NULL, 'Carl Critchlow', 2, 231, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 2, 'Donato Giancola', 0, 232, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V',  NULL, NULL, 'Jim Nelson', 0, 233, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'VVV', 1, 1, 'John Avon', 2, 234, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4VV', 3, 4, 'Eric Peterson', 1, 235, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2V',  NULL, NULL, 'Jeff Remmer', 1, 236, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Gary Ruddell', 0, 237, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Mark Zug', 0, 238, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1V',  NULL, NULL, 'Greg & Tim Hildebrandt', 1, 239, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2VV',  NULL, NULL, 'Anthony S. Waters', 0, 240, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 4, 4, 'Heather Hudson', 1, 241, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1V',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 242, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Rebecca Guay', 2, 243, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Greg Staples', 1, 244, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'XV', 0, 0, 'Ron Spencer', 2, 245, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 3, 'Ron Spears', 0, 246, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 3, 1, 'D. Alexander Gregory', 0, 247, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 1, 1, 'Kev Walker', 2, 248, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', 2, 2, 'Greg & Tim Hildebrandt', 0, 249, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 3, 3, 'Thomas M. Baxa', 1, 250, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Rebecca Guay', 0, 251, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Gary Ruddell', 0, 252, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Justin Sweet', 0, 253, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 2, 'Daren Bader', 1, 254, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 1, 'John Matson', 2, 255, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Rebecca Guay', 2, 256, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'XV',  NULL, NULL, 'Ron Spencer', 2, 257, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Terese Nielson', 1, 258, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5V', 1, 1, 'Christopher Moeller', 2, 259, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2VVV',  NULL, NULL, 'Carl Critchlow', 1, 260, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V',  NULL, NULL, 'Greg & Tim Hildebrandt', 1, 261, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', 'V',  NULL, NULL, 'Alex Horley', 0, 262, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4V', 3, 4, 'Dave Dorman', 0, 263, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2V',  NULL, NULL, 'Keith Garletts', 0, 264, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '1V',  NULL, NULL, 'Bradley Williams', 0, 265, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '6V',  NULL, NULL, 'Kev Walker', 1, 266, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'VVV', 2, 2, 'Greg Staples', 2, 267, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2V',  NULL, NULL, 'Ciruelo', 0, 268, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V',  NULL, NULL, 'Greg & Tim Hildebrandt', 0, 269, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 2, 'Jerry Tiritilli', 1, 270, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 3, 2, 'Rick Farrell', 2, 271, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 3, 3, 'Arnie Swekel', 0, 272, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', 2, 2, 'Carl Critchlow', 2, 273, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Anthony S. Waters', 1, 274, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1VV',  NULL, NULL, 'Matt Cavatto', 1, 275, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4VVV', 4, 5, 'Wayne England', 2, 276, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V',  NULL, NULL, 'Arnie Swekel', 1, 277, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', -1, -1, 'Jim Nelson', 2, 278, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 2, 'Carl Critchlow', 1, 279, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '4V',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 280, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2V',  NULL, NULL, 'Greg Staples', 1, 281, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 1, 'Carl Critchlow', 0, 282, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 2, 'Anthony S. Waters', 0, 283, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 2, 'Rick Farrell', 0, 284, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 1, 2, 'Alex Horley', 2, 285, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', 'WBNRV', 5, 5, 'Ron Spears', 2, 286, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'rituel', '2RV',  NULL, NULL, 'Alex Horley', 2, 287, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '5WB', 4, 4, 'Matt Cavatto', 2, 288, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1RV', 1, 2, 'Franz Vohwinkel', 1, 289, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '2VW', 3, 3, 'Gary Ruddell', 2, 290, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1WB', 1, 2, 'Glen Angus', 1, 291, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1BN', 1, 2, 'Edward P. Beard, Jr.', 1, 292, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1NR', 1, 2, 'Mark Brill', 1, 293, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1BN', 1, 3, 'Rick Farrell', 2, 294, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1VW', 1, 2, 'Monte Michael Moore', 1, 295, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '6NR', 5, 5, 'Gary Ruddell', 2, 296, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '2',  NULL, NULL, 'Tony Szczudlo', 2, 297, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4',  NULL, NULL, 'Anthony S. Waters', 2, 298, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 299, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4', 0, 0, 'Brian Snoddy', 2, 300, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '6', 3, 4, 'Mark Tedin', 1, 301, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '2', 0, 1, 'Alex Horley', 1, 302, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'creature', '5',  NULL, NULL, 'Donato Giancola', 2, 303, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 304, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4', 2, 3, 'Brian Snoddy', 2, 305, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '3', 2, 1, 'Jerry Tiritilli', 1, 306, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '3',  NULL, NULL, 'Jim Nelson', 1, 307, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '4',  NULL, NULL, 'David Martin', 1, 308, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 309, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '2',  NULL, NULL, 'Jim Nelson', 1, 310, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 311, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Edward P. Beard, Jr.', 0, 312, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 313, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Brian Snoddy', 0, 314, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 315, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 316, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 317, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 2, 318, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Monte Michael Moore', 2, 319, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 2, 320, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 2, 321, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 1, 322, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Glen Angus', 2, 323, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 0, 324, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 325, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Glen Angus', 2, 326, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 2, 327, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Ron Spencer', 2, 328, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 2, 329, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 330, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 331, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Don Hazeltine', 0, 332, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Eric Peterson', 0, 333, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 334, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 335, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Ben Thompson', 0, 336, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 337, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 338, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Jerry Tiritilli', 0, 339, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Arnie Swekel', 0, 340, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 341, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 342, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Anthony S. Waters', 0, 343, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Franz Vohwinkel', 0, 344, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 345, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Tony Szczudlo', 0, 346, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 347, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 348, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Jerry Tiritilli', 0, 349, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T',  NULL, NULL, 'Tony Szczudlo', 0, 350, 'ODI'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '6W', 5, 5, 'rk post', 2, 1, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 1, 'Greg Staples', 0, 2, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '1WW', NULL, NULL, 'Ron Spears', 1, 3, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Greg & Tim Hildebrandt', 1, 4, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Keith Garletts', 0, 5, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W', NULL, NULL, 'Mark Brill', 0, 6, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Christopher Moeller', 1, 7, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 3, 'Daren Bader', 2, 8, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 1, 'Mark Brill', 0, 9, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '1W', NULL, NULL, 'Tony Szczudlo', 2, 10, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 2, 'Edward P. Beard, Jr.', 0, 11, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'W', NULL, NULL, 'Adam Rex', 0, 12, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 3, 3, 'Eric Peterson', 2, 13, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Gary Ruddell', 2, 14, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '3W', NULL, NULL, 'rk post', 0, 15, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Matt Cavotta', 1, 16, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Jerry Tiritilli', 1, 17, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 1, 4, 'Greg & Tim Hildebrandt', 0, 18, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 3, 'Greg & Tim Hildebrandt', 1, 19, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '3WWW', NULL, NULL, 'Rebecca Guay', 2, 20, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'WW', NULL, NULL, 'Mark Tedin', 2, 21, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Justin Sweet', 2, 22, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1BB', 1, 3, 'Eric Peterson', 2, 23, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 3, 'Arnie Swekel', 0, 24, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'DiTerlizzi', 1, 25, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'XB', NULL, NULL, 'Gary Ruddell', 1, 26, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 3, 3, 'Rob Alexander', 0, 27, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Pete Venters', 1, 28, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 3, 'Keith Garletts', 1, 29, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Jerry Tiritilli', 0, 30, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 1, 1, 'Alex Horley', 2, 31, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B', NULL, NULL, 'Thomas M. Baxa', 0, 32, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Anthony S. Waters', 1, 33, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'Christopher Moeller', 1, 34, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', 'B', NULL, NULL, 'Roger Raupp', 0, 35, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '3B', NULL, NULL, 'Daren Bader', 0, 36, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Ron Spencer', 2, 37, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'David Martin', 0, 38, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 2, 'Glen Angus', 0, 39, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 3, 3, 'Arnie Swekel', 1, 40, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Ron Spencer', 0, 41, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 3, 'Mark Zug', 2, 42, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Jim Nelson', 0, 43, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3B', NULL, NULL, 'Ben Thompson', 2, 44, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2BB', 3, 3, 'Scott M. Fischer', 2, 45, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'B', NULL, NULL, 'Greg Staples', 2, 46, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 1, 'Matt Cavotta', 0, 47, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'Bradley Williams', 1, 48, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', 'BB', NULL, NULL, 'Wayne England', 2, 49, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Ron Spencer', 1, 50, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N', NULL, NULL, 'Greg & Tim Hildebrandt', 0, 51, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 1, 'Donato Giancola', 0, 52, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1NN', 1, 1, 'Pete Venters', 0, 53, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 2, 1, 'Edward P. Beard, Jr.', 0, 54, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 6, 5, 'Glen Angus', 1, 55, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 3, 3, 'Mark Zug', 2, 56, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N', NULL, NULL, 'Ben Thompson', 1, 57, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1NN', NULL, NULL, 'Heather Hudson', 0, 58, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '2NNN', NULL, NULL, 'Pete Venters', 2, 59, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 3, 'Daren Bader', 0, 60, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Adam Rex', 1, 61, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 2, 'Daren Bader', 0, 62, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 3, 3, 'Terese Nielsen', 1, 63, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '8NNN', 8, 8, 'Greg Staples', 2, 64, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 3, 1, 'rk post', 2, 65, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '3N', NULL, NULL, 'John Avon', 2, 66, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4NN', 6, 3, 'Greg Staples', 2, 67, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '2NN', NULL, NULL, 'John Matson', 2, 68, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1N', 1, 1, 'Dana Knutson', 0, 69, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '4N', NULL, NULL, 'Eric Peterson', 1, 70, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '2NN', NULL, NULL, 'Mike Ploog', 2, 71, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN', NULL, NULL, 'Christopher Moeller', 1, 72, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2NN', NULL, NULL, 'Eric Peterson', 2, 73, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'NN', 2, 1, 'Brian Snoddy', 2, 74, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 3, 1, 'Adam Rex', 0, 75, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '2NN', NULL, NULL, 'Alex Horley', 0, 76, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 1, 1, 'Wayne England', 0, 77, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1NN', NULL, NULL, 'Ciruelo', 0, 78, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N', NULL, NULL, 'John Matson', 0, 79, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 4, 4, 'Kev Walker', 2, 80, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1NN', NULL, NULL, 'Clyde Caldwell', 0, 81, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1NNN', 3, 3, 'Arnie Swekel', 2, 82, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1N', NULL, NULL, 'Scott M. Fischer', 1, 83, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '1NN', 1, 1, 'John Avon', 1, 84, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 3, 2, 'Carl Critchlow', 0, 85, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'enchantement', '1N', NULL, NULL, 'Greg & Tim Hildebrandt', 1, 86, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '2N', NULL, NULL, 'Keith Garletts', 0, 87, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '4N', NULL, NULL, 'Alan Pollack', 0, 88, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'NNN', 2, 2, 'Brian Snoddy', 1, 89, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R', NULL, NULL, 'Gary Ruddell', 0, 90, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1RR', 2, 2, 'Ron Spears', 2, 91, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1R', 2, 2, 'Mark Tedin', 0, 92, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', 'R', NULL, NULL, 'Mike Ploog', 0, 93, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '5RR', 4, 4, 'Ron Spears', 1, 94, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'RR', NULL, NULL, 'Tony Szczudlo', 2, 95, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Terese Nielsen', 0, 96, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1RR', NULL, NULL, 'Greg & Tim Hildebrandt', 0, 97, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'XR', NULL, NULL, 'Donato Giancola', 1, 98, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R', NULL, NULL, 'Carl Critchlow', 0, 99, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Jim Nelson', 2, 100, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '1RR', 2, 2, 'Mike Ploog', 2, 101, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '5RR', NULL, NULL, 'Don Hazeltine', 0, 102, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 3, 2, 'Glen Angus', 0, 103, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'R', NULL, NULL, 'Anthony S. Waters', 2, 104, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 3, 3, 'rk post', 1, 105, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Pete Venters', 1, 106, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '4R', 3, 2, 'Justin Sweet', 0, 107, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '6RR', 5, 6, 'Jim Nelson', 2, 108, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Wayne England', 0, 109, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 5, 'David Martin', 1, 110, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 3, 3, 'Scott M. Fischer', 2, 111, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R', NULL, NULL, 'Christopher Moeller', 1, 112, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '3RR', NULL, NULL, 'Carl Critchlow', 2, 113, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'RR', NULL, NULL, 'Bradley Williams', 2, 114, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R', NULL, NULL, 'Terese Nielsen', 0, 115, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '3R', NULL, NULL, 'Mark Romanoski', 1, 116, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1RRR', NULL, NULL, 'Bob Petillo', 1, 117, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '3V', NULL, NULL, 'Edward P. Beard, Jr.', 0, 118, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 3, 3, 'Bob Petillo', 1, 119, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 4, 4, 'John Avon', 1, 120, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Heather Hudson', 0, 121, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 3, 3, 'Justin Sweet', 1, 122, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5V', 3, 3, 'Mark Zug', 0, 123, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V', NULL, NULL, 'Rebecca Guay', 1, 124, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2V', NULL, NULL, 'Darrell Riche', 0, 125, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 6, 8, 'Scott M. Fischer', 2, 126, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'V', NULL, NULL, 'Franz Vohwinkel', 2, 127, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2VV', NULL, NULL, 'Rebecca Guay', 0, 128, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Jim Nelson', 0, 129, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 2, 'Clyde Caldwell', 0, 130, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 2, 'Matt Cavotta', 2, 131, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2VV', 2, 3, 'Mark Romanoski', 0, 132, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Darrell Riche', 2, 133, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2V', NULL, NULL, 'Christopher Moeller', 1, 134, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', 'VV', NULL, NULL, 'Darrell Riche', 2, 135, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '3VV', NULL, NULL, 'Matt Cavotta', 2, 136, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2VV', 3, 3, 'Alex Horley', 2, 137, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 1, 'Mark Romanoski', 1, 138, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 139, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 140, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Alan Pollack', 1, 141, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Tony Szczudlo', 1, 142, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Rob Alexander', 1, 143, 'TOR'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '5WW', 4, 4, 'Pete Venters', 1, 1, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W', NULL, NULL, 'Roger Raupp', 1, 2, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '2WW', NULL, NULL, 'Randy Gallegos', 1, 3, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 2, 'Wayne England', 0, 4, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Roger Raupp', 0, 5, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '4W', 1, 6, 'Roger Raupp', 0, 6, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Scott M. Fischer', 0, 7, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '3W', NULL, NULL, 'Carl Critchlow', 1, 8, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2WW', 2, 4, 'Rebecca Guay', 2, 9, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', 'W', NULL, NULL, 'Carl Critchlow', 0, 10, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 3, 3, 'Donato Giancola', 2, 11, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'rituel', '3WW', NULL, NULL, 'Alan Pollack', 2, 12, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Dave Dorman', 0, 13, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Adam Rex', 0, 14, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 2, 2, 'Eric Peterson', 2, 15, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 0, 0, 'David Martin', 1, 16, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 0, 0, 'Jim Nelson', 0, 17, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '2W', NULL, NULL, 'Eric Peterson', 0, 18, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Jeff Easley', 2, 19, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'ephemere', '1W', NULL, NULL, 'Doug Chaffee', 0, 20, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3WW', 3, 4, 'Christopher Moeller', 2, 21, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '2W', 1, 3, 'Christopher Moeller', 0, 22, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '5WWW', 6, 6, 'Matthew D. Wilson', 2, 23, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Scott M. Fischer', 2, 24, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '1W', NULL, NULL, 'Rob Alexander', 1, 25, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Gary Ruddell', 1, 26, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Ron Spears', 1, 27, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', 'W', 1, 1, 'Heather Hudson', 0, 28, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2WW', NULL, NULL, 'Mike Ploog', 2, 29, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1W', 1, 1, 'John Matson', 0, 30, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'enchantement', '2W', NULL, NULL, 'Alex Horley', 1, 31, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '3W', 2, 2, 'Kev Walker', 1, 32, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('W', 'creature', '1WW', 2, 2, 'Eric Peterson', 0, 33, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 1, 'Edward P. Beard, Jr.', 0, 34, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1BB', 1, 1, 'Alan Pollack', 2, 35, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 1, 'Tony Szczudlo', 1, 36, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Jim Nelson', 2, 37, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Ben Thompson', 0, 38, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Don Hazeltine', 0, 39, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'X1B', NULL, NULL, 'Ben Thompson', 1, 40, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Bradley Williams', 0, 41, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', 'B', 1, 1, 'Ron Spears', 0, 42, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '2B', NULL, NULL, 'Fred Rahmqvist', 0, 43, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '1B', NULL, NULL, 'Pete Venters', 1, 44, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '1B', NULL, NULL, 'Ben Thompson', 0, 45, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', 'B', NULL, NULL, 'Bradley Williams', 0, 46, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 3, 4, 'Mark Brill', 0, 47, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '3BB', NULL, NULL, 'Mike Ploog', 2, 48, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'rituel', '1B', NULL, NULL, 'John Avon', 1, 49, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '4B', 1, 5, 'Mark Tedin', 2, 50, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'ephemere', '3BBB', NULL, NULL, 'Pete Venters', 2, 51, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2BBB', NULL, NULL, 'Jim Nelson', 2, 52, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'enchantement', '2B', NULL, NULL, 'Don Hazeltine', 1, 53, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 2, 2, 'Rebecca Guay', 1, 54, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3BB', 5, 5, 'Heather Hudson', 2, 55, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '3B', 3, 6, 'Glen Angus', 1, 56, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 3, 4, 'Thomas M. Baxa', 0, 57, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '5BB', 6, 1, 'Heather Hudson', 2, 58, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '1B', 2, 2, 'Doug Chaffee', 0, 59, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('B', 'creature', '2B', 2, 4, 'John Avon', 1, 60, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2NN', 2, 2, 'Carl Critchlow', 2, 61, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'N', NULL, NULL, 'Ron Spencer', 1, 62, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', 'N', 1, 1, 'Pete Venters', 0, 63, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '1NN', NULL, NULL, 'Jeff Easley', 2, 64, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 1, 'Heather Hudson', 0, 65, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3N', 2, 2, 'Thomas M. Baxa', 1, 66, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N', NULL, NULL, 'Tim Hildebrandt', 1, 67, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '3NN', 0, 4, 'Mark Tedin', 2, 68, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 5, 5, 'Matthew D. Wilson', 2, 69, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', '5NN', NULL, NULL, 'Jerry Tiritilli', 2, 70, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'XN', NULL, NULL, 'Bob Petillo', 0, 71, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'rituel', 'NN', NULL, NULL, 'Arnie Swekel', 1, 72, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4NNN', -1, -1, 'Carl Critchlow', 2, 73, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'ephemere', '1N', NULL, NULL, 'Bradley Williams', 0, 74, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '4N', 4, 4, 'Kev Walker', 1, 75, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('N', 'creature', '2N', 2, 2, 'Mark Tedin', 0, 76, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'John Avon', 1, 77, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R', NULL, NULL, 'Mark Brill', 0, 78, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2R', 2, 2, 'Mike Ploog', 0, 79, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R', NULL, NULL, 'Dave Dorman', 0, 80, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1RR', NULL, NULL, 'Matthew D. Wilson', 2, 81, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '2R', NULL, NULL, 'Mark Tedin', 1, 82, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '1R', NULL, NULL, 'Scott M. Fischer', 2, 83, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'RRR', 2, 2, 'Arnie Swekel', 2, 84, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 2, 2, 'Edward P. Beard, Jr.', 1, 85, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Thomas M. Baxa', 0, 86, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '6R', NULL, NULL, 'Alan Pollack', 0, 87, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', 'XRR', NULL, NULL, 'David Martin', 1, 88, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '1R', NULL, NULL, 'Glen Angus', 0, 89, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 2, 2, 'Greg Staples', 2, 90, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '5R', 2, 2, 'Keith Garletts', 0, 91, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '1R', NULL, NULL, 'Christopher Moeller', 1, 92, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '2RR', 3, 1, 'rk post', 2, 93, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', 'R', NULL, NULL, 'Darrell Riche', 0, 94, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', 'R', 1, 1, 'Greg Hildebrandt', 0, 95, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3RR', NULL, NULL, 'Ron Spears', 2, 96, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'enchantement', '2R', NULL, NULL, 'Ron Spencer', 1, 97, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'ephemere', '2R', NULL, NULL, 'Greg Hildebrandt', 2, 98, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3RR', 6, 6, 'John Matson', 1, 99, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3R', 3, 1, 'Mark Romanoski', 0, 100, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R', NULL, NULL, 'Ben Thompson', 1, 101, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'rituel', '3R', NULL, NULL, 'Tony Szczudlo', 0, 102, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('R', 'creature', '3RRR', 7, 7, 'Wayne England', 2, 103, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1VV', 2, 2, 'Randy Gallegos', 0, 104, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 4, 'John Matson', 1, 105, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3VV', 3, 3, 'Daren Bader', 0, 106, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 3, 3, 'Matt Cavotta', 1, 107, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', 'V', NULL, NULL, 'Matthew Mitchell', 0, 108, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 2, 2, 'Eric Peterson', 0, 109, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '6VVV', NULL, NULL, 'Christopher Moeller', 2, 110, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2V', NULL, NULL, 'Jim Nelson', 1, 111, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '2VV', NULL, NULL, 'Greg & Tim Hildebrandt', 2, 112, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '3V', 4, 5, 'Greg Staples', 2, 113, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'enchantement', '1V', NULL, NULL, 'Wayne England', 1, 114, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '2V', NULL, NULL, 'Matt Cavotta', 0, 115, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 1, 'Darrell Riche', 1, 116, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '4V', 4, 4, 'Mark Zug', 2, 117, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5V', 5, 5, 'Kev Walker', 0, 118, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '3VV', NULL, NULL, 'Dave Dorman', 1, 119, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 1, 'David Martin', 0, 120, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 1, 1, 'Heather Hudson', 0, 121, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V', NULL, NULL, 'Gary Ruddell', 1, 122, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Edward P. Beard, Jr.', 0, 123, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '1V', NULL, NULL, 'Eric Peterson', 2, 124, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '1V', 2, 1, 'Greg Staples', 0, 125, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 2, 3, 'Darrell Riche', 0, 126, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2VV', 2, 0, 'Carl Critchlow', 1, 127, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 0, 0, 'Wayne England', 2, 128, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '2V', 1, 0, 'Brian Snoddy', 0, 129, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '1V', NULL, NULL, 'Rebecca Guay', 2, 130, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', 'XV', NULL, NULL, 'David Martin', 1, 131, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'ephemere', '3V', NULL, NULL, 'Alan Pollack', 0, 132, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', 'V', 1, 1, 'Pete Venters', 2, 133, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '5VV', 5, 5, 'John Avon', 2, 134, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'creature', '6VV', 6, 6, 'Jeff Easley', 1, 135, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('V', 'rituel', '2VV', NULL, NULL, 'Ron Spencer', 0, 136, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '1VW', 3, 4, 'Arnie Swekel', 2, 137, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('M', 'enchantement', 'VW', NULL, NULL, 'Mark Brill', 2, 138, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('M', 'enchantement', '3VW', NULL, NULL, 'David Martin', 2, 139, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('M', 'creature', '5VW', 0, 0, 'Arnie Swekel', 2, 140, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Tony Szczudlo', 1, 141, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Rob Alexander', 1, 142, 'JUD'); 
INSERT INTO carte_virtuelle VALUES ('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 143, 'JUD'); 
