INSERT INTO carte_virtuelle(carte_couleur, carte_type, carte_cout, carte_force, carte_endurance, carte_artiste, carte_rarete, carte_ordre_serie, ser_code) VALUES
('W', 'enchantement', 'W',  NULL, NULL, 'Ron Spears', 2, 1, 'ODY'), 
('W', 'rituel', '5WW',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 2, 'ODY'), 
('W', 'creature', '1W', 0, 4, 'John Avon', 0, 3, 'ODY'), 
('W', 'enchantement', '2W',  NULL, NULL, 'Edward P. Beard, Jr.', 1, 4, 'ODY'), 
('W', 'creature', '2W', 2, 2, 'Rebecca Guay', 0, 5, 'ODY'), 
('W', 'creature', '3WW', 2, 2, 'Mark Zug', 1, 6, 'ODY'), 
('W', 'creature', '3W', 2, 2, 'Justin Sweet', 0, 7, 'ODY'), 
('W', 'creature', '4W', 2, 3, 'Greg & Tim Hildebrandt', 0, 8, 'ODY'), 
('W', 'enchantement', '1WW',  NULL, NULL, 'Wayne England', 2, 9, 'ODY'), 
('W', 'rituel', '2WW',  NULL, NULL, 'Scott M. Fischer', 2, 10, 'ODY'), 
('W', 'creature', '1W', 1, 1, 'Darrell Riche', 1, 11, 'ODY'), 
('W', 'creature', '3W', 1, 4, 'Terese Nielson', 1, 12, 'ODY'), 
('W', 'creature', '1WW', -1, -1, 'Daren Bader', 2, 13, 'ODY'), 
('W', 'ephemere', '2W',  NULL, NULL, 'Darrell Riche', 0, 14, 'ODY'), 
('W', 'creature', 'W', 1, 1, 'John Avon', 0, 15, 'ODY'), 
('W', 'creature', 'W', 1, 1, 'Dave Dorman', 0, 16, 'ODY'), 
('W', 'enchantement', '3W',  NULL, NULL, 'Luca Zontini', 2, 17, 'ODY'), 
('W', 'creature', 'W', 1, 2, 'Clyde Caldwell', 2, 18, 'ODY'), 
('W', 'enchantement', '1WW',  NULL, NULL, 'Ray Lago', 2, 19, 'ODY'), 
('W', 'creature', '2W', 1, 1, 'rk post', 2, 20, 'ODY'), 
('W', 'enchantement', '1W',  NULL, NULL, 'Heather Hudson', 2, 21, 'ODY'), 
('W', 'ephemere', '2W',  NULL, NULL, 'Rebecca Guay', 0, 22, 'ODY'), 
('W', 'ephemere', '1W',  NULL, NULL, 'Mark Tedin', 1, 23, 'ODY'), 
('W', 'creature', '2WW', 1, 4, 'Heather Hudson', 2, 24, 'ODY'), 
('W', 'creature', '2W', 1, 1, 'Ben Thompson', 0, 25, 'ODY'), 
('W', 'enchantement', '2W',  NULL, NULL, 'Ray Lago', 2, 26, 'ODY'), 
('W', 'enchantement', 'W',  NULL, NULL, 'Pete Venters', 0, 27, 'ODY'), 
('W', 'rituel', '4WW',  NULL, NULL, 'Kev Walker', 2, 28, 'ODY'), 
('W', 'creature', '1WW', 2, 2, 'Paolo Parente', 2, 29, 'ODY'), 
('W', 'ephemere', '1W',  NULL, NULL, 'John Avon', 0, 30, 'ODY'), 
('W', 'creature', '3W', 1, 4, 'Terese Nielson', 1, 31, 'ODY'), 
('W', 'creature', 'WWW', 2, 2, 'Terese Nielson', 2, 32, 'ODY'), 
('W', 'creature', '1WW', 2, 1, 'Kev Walker', 2, 33, 'ODY'), 
('W', 'creature', 'W', 1, 1, 'Larry Elmore', 1, 34, 'ODY'), 
('W', 'creature', '1W', 2, 1, 'Matt Cavatto', 0, 35, 'ODY'), 
('W', 'creature', '3W', 2, 4, 'Paolo Parente', 0, 36, 'ODY'), 
('W', 'creature', '2W', 1, 2, 'Pete Venters', 1, 37, 'ODY'), 
('W', 'creature', '1W', 2, 2, 'Daren Bader', 0, 38, 'ODY'), 
('W', 'creature', '1WW', 2, 2, 'D. Alexander Gregory', 2, 39, 'ODY'), 
('W', 'creature', '2W', 1, 3, 'Orizio Daniele', 0, 40, 'ODY'), 
('W', 'creature', '2W', 1, 3, 'Massimilano Frezzato', 0, 41, 'ODY'), 
('W', 'ephemere', '3W',  NULL, NULL, 'Carl Critchlow', 0, 42, 'ODY'), 
('W', 'creature', '2WW', 2, 3, 'Clyde Caldwell', 1, 43, 'ODY'), 
('W', 'ephemere', 'W',  NULL, NULL, 'Bradley Williams', 0, 44, 'ODY'), 
('W', 'ephemere', '4W',  NULL, NULL, 'Ray Lago', 0, 45, 'ODY'), 
('W', 'ephemere', '1W',  NULL, NULL, 'Christopher Moeller', 0, 46, 'ODY'), 
('W', 'creature', '1W', 1, 1, 'Ron Spencer', 1, 47, 'ODY'), 
('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 48, 'ODY'), 
('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 49, 'ODY'), 
('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 50, 'ODY'), 
('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 51, 'ODY'), 
('W', 'enchantement', '3W',  NULL, NULL, 'Christopher Moeller', 1, 52, 'ODY'), 
('W', 'ephemere', '2W',  NULL, NULL, 'Christopher Moeller', 1, 53, 'ODY'), 
('W', 'enchantement', '2W',  NULL, NULL, 'Ben Thompson', 1, 54, 'ODY'), 
('W', 'enchantement', 'W',  NULL, NULL, 'Roger Raupp', 1, 55, 'ODY'), 
('W', 'creature', 'W', 1, 1, 'Carl Critchlow', 0, 56, 'ODY'), 
('W', 'creature', '4WW', 4, 4, 'Mark Tedin', 2, 57, 'ODY'), 
('B', 'creature', '4BB', 3, 3, 'Christopher Moeller', 2, 58, 'ODY'), 
('B', 'enchantement', 'B',  NULL, NULL, 'Ciruelo', 0, 59, 'ODY'), 
('B', 'ephemere', '1B',  NULL, NULL, 'Adam Rex', 0, 60, 'ODY'), 
('B', 'creature', '5BB', 6, 6, 'Heather Hudson', 2, 61, 'ODY'), 
('B', 'ephemere', '1B',  NULL, NULL, 'Ray Lago', 1, 62, 'ODY'), 
('B', 'creature', '3B', 2, 2, 'Christopher Moeller', 0, 63, 'ODY'), 
('B', 'creature', '2BB', 2, 3, 'Kev Walker', 1, 64, 'ODY'), 
('B', 'creature', '3BB', 3, 3, 'Greg & Tim Hildebrandt', 0, 65, 'ODY'), 
('B', 'creature', '2B', 1, 1, 'Ray Lago', 1, 66, 'ODY'), 
('B', 'creature', '3BB', 3, 2, 'Wayne England', 1, 67, 'ODY'), 
('B', 'rituel', '2B',  NULL, NULL, 'Alan Pollack', 1, 68, 'ODY'), 
('B', 'enchantement', '3BB',  NULL, NULL, 'Mark Brill', 2, 69, 'ODY'), 
('B', 'rituel', 'B',  NULL, NULL, 'Scott M. Fischer', 0, 70, 'ODY'), 
('B', 'creature', '3B', 2, 2, 'Dave Dorman', 1, 71, 'ODY'), 
('B', 'creature', '2B', 2, 1, 'Keith Garletts', 0, 72, 'ODY'), 
('B', 'creature', '2BB', 2, 3, 'Tony Szczudlo', 2, 73, 'ODY'), 
('B', 'creature', '1B', 1, 1, 'Alan Pollack', 0, 74, 'ODY'), 
('B', 'enchantement', '1BB',  NULL, NULL, 'Wayne England', 2, 75, 'ODY'), 
('B', 'enchantement', '2BB',  NULL, NULL, 'Wayne England', 1, 76, 'ODY'), 
('B', 'creature', '6BB', -1, -1, 'Adam Rex', 2, 77, 'ODY'), 
('B', 'rituel', '2BB',  NULL, NULL, 'Glen Angus & Arnie Swekel', 1, 78, 'ODY'), 
('B', 'rituel', '4BB',  NULL, NULL, 'Daren Bader', 2, 79, 'ODY'), 
('B', 'ephemere', '2B',  NULL, NULL, 'Wayne England', 1, 80, 'ODY'), 
('B', 'rituel', '3B',  NULL, NULL, 'Mike Ploog', 0, 81, 'ODY'), 
('B', 'ephemere', 'B',  NULL, NULL, 'Christopher Moeller', 2, 82, 'ODY'), 
('B', 'creature', '3B', 4, 3, 'Wayne England', 0, 83, 'ODY'), 
('B', 'creature', '1B', 1, 1, 'Scott M. Fischer', 0, 84, 'ODY'), 
('B', 'rituel', 'B',  NULL, NULL, 'Matt Cavatto', 2, 85, 'ODY'), 
('B', 'ephemere', '3BB',  NULL, NULL, 'Scott M. Fischer', 1, 86, 'ODY'), 
('B', 'enchantement', '1B',  NULL, NULL, 'Darrell Riche', 0, 87, 'ODY'), 
('B', 'rituel', '4B',  NULL, NULL, 'Don Hazeltine', 1, 88, 'ODY'), 
('B', 'creature', 'BBB', 2, 2, 'Donato Giancola', 2, 89, 'ODY'), 
('B', 'enchantement', 'BB',  NULL, NULL, 'Heather Hudson', 2, 90, 'ODY'), 
('B', 'ephemere', 'B',  NULL, NULL, 'Adam Rex', 0, 91, 'ODY'), 
('B', 'enchantement', '3BB',  NULL, NULL, 'Adam Rex', 2, 92, 'ODY'), 
('B', 'creature', '1B', 2, 2, 'Wayne England', 0, 93, 'ODY'), 
('B', 'ephemere', '1B',  NULL, NULL, 'Rebecca Guay', 1, 94, 'ODY'), 
('B', 'enchantement', '1B',  NULL, NULL, 'Orizio Daniele', 0, 95, 'ODY'), 
('B', 'creature', '4B', 0, 1, 'Arnie Swekel', 1, 96, 'ODY'), 
('B', 'creature', '2B', 1, 2, 'Scott M. Fischer', 1, 97, 'ODY'), 
('B', 'ephemere', '3B',  NULL, NULL, 'Terese Nielson', 0, 98, 'ODY'), 
('B', 'ephemere', '1B',  NULL, NULL, 'Bradley Williams', 0, 99, 'ODY'), 
('B', 'creature', '4B', 2, 2, 'Kev Walker', 0, 100, 'ODY'), 
('B', 'creature', '2B', 1, 1, 'Greg Staples', 2, 101, 'ODY'), 
('B', 'enchantement', '1B',  NULL, NULL, 'Heather Hudson', 1, 102, 'ODY'), 
('B', 'ephemere', 'XB',  NULL, NULL, 'Pete Venters', 0, 103, 'ODY'), 
('B', 'enchantement', '2B',  NULL, NULL, 'Jim Nelson', 1, 104, 'ODY'), 
('B', 'creature', '2BB', 4, 4, 'Jim Nelson', 2, 105, 'ODY'), 
('B', 'creature', '1B', 2, 2, 'Luca Zontini', 1, 106, 'ODY'), 
('B', 'creature', 'B', 1, 1, 'Arnie Swekel', 0, 107, 'ODY'), 
('B', 'rituel', '8BB',  NULL, NULL, 'Paolo Parente', 2, 108, 'ODY'), 
('B', 'rituel', '3B',  NULL, NULL, 'Eric Peterson', 0, 109, 'ODY'), 
('B', 'rituel', '3BB',  NULL, NULL, 'Greg Staples', 2, 110, 'ODY'), 
('B', 'creature', '2BB', 2, 3, 'Carl Critchlow', 1, 111, 'ODY'), 
('B', 'enchantement', '1B',  NULL, NULL, 'Ron Spencer', 2, 112, 'ODY'), 
('B', 'rituel', '4BB',  NULL, NULL, 'Kev Walker', 2, 113, 'ODY'), 
('B', 'ephemere', '1B',  NULL, NULL, 'Eric Peterson', 0, 114, 'ODY'), 
('N', 'ephemere', '2N',  NULL, NULL, 'Roger Raupp', 0, 115, 'ODY'), 
('N', 'creature', '1N', 1, 1, 'Adam Rex', 2, 116, 'ODY'), 
('N', 'creature', '2NN', 2, 2, 'Eric Peterson', 2, 117, 'ODY'), 
('N', 'rituel', '2N',  NULL, NULL, 'Greg Staples', 1, 118, 'ODY'), 
('N', 'creature', '1N', 1, 1, 'Alex Horley', 0, 119, 'ODY'), 
('N', 'creature', '3NNN', 5, 5, 'Mark Zug', 2, 120, 'ODY'), 
('N', 'enchantement', '1NN',  NULL, NULL, 'Ben Thompson', 2, 121, 'ODY'), 
('N', 'enchantement', '4NN',  NULL, NULL, 'John Avon', 1, 122, 'ODY'), 
('N', 'creature', '3N', 2, 2, 'Larry Elmore', 1, 123, 'ODY'), 
('N', 'ephemere', 'N',  NULL, NULL, 'Pete Venters', 0, 124, 'ODY'), 
('N', 'creature', '1N', 2, 1, 'John Matson', 0, 125, 'ODY'), 
('N', 'creature', '4N', 4, 3, 'Jeff Remmer', 2, 126, 'ODY'), 
('N', 'enchantement', '1NN',  NULL, NULL, 'Don Hazeltine', 2, 127, 'ODY'), 
('N', 'rituel', '1N',  NULL, NULL, 'Tony Szczudlo', 1, 128, 'ODY'), 
('N', 'rituel', '2NN',  NULL, NULL, 'Rick Farrell', 1, 129, 'ODY'), 
('N', 'creature', '3N', 2, 3, 'Daren Bader', 0, 130, 'ODY'), 
('N', 'creature', '2N', 2, 1, 'Edward P. Beard, Jr.', 0, 131, 'ODY'), 
('N', 'ephemere', 'N',  NULL, NULL, 'Ron Spears', 2, 132, 'ODY'), 
('N', 'ephemere', '2N',  NULL, NULL, 'Gary Ruddell', 1, 133, 'ODY'), 
('N', 'creature', '5N', 3, 4, 'Thomas M. Baxa', 1, 134, 'ODY'), 
('N', 'creature', '3N', 3, 2, 'Adam Rex', 1, 135, 'ODY'), 
('N', 'creature', '1N', 2, 2, 'Adam Rex', 0, 136, 'ODY'), 
('N', 'creature', '2N', 2, 2, 'John Matson', 0, 137, 'ODY'), 
('N', 'creature', '1N', 1, 1, 'Matt Cavatto', 0, 138, 'ODY'), 
('N', 'ephemere', 'N',  NULL, NULL, 'Gary Ruddell', 0, 139, 'ODY'), 
('N', 'creature', '3N', 2, 2, 'Tony Szczudlo', 0, 140, 'ODY'), 
('N', 'enchantement', 'NNN',  NULL, NULL, 'Alex Horley', 2, 141, 'ODY'), 
('N', 'rituel', '3NN',  NULL, NULL, 'Arnie Swekel', 2, 142, 'ODY'), 
('N', 'rituel', '2N',  NULL, NULL, 'Luca Zontini', 2, 143, 'ODY'), 
('N', 'creature', '2N', 1, 1, 'Anthony S. Waters', 1, 144, 'ODY'), 
('N', 'rituel', 'N',  NULL, NULL, 'Carl Critchlow', 0, 145, 'ODY'), 
('N', 'rituel', '2N',  NULL, NULL, 'Bradley Williams', 0, 146, 'ODY'), 
('N', 'enchantement', '1NN',  NULL, NULL, 'Alex Horley', 1, 147, 'ODY'), 
('N', 'rituel', '1N',  NULL, NULL, 'Marc Fishman', 0, 148, 'ODY'), 
('N', 'creature', '2NN', 4, 3, 'Kev Walker', 2, 149, 'ODY'), 
('N', 'rituel', '4NN',  NULL, NULL, 'Eric Peterson', 0, 150, 'ODY'), 
('N', 'rituel', '1N',  NULL, NULL, 'Justin Sweet', 0, 151, 'ODY'), 
('N', 'creature', '2NN', -1, -1, 'Anthony S. Waters', 2, 152, 'ODY'), 
('N', 'enchantement', 'NNNN',  NULL, NULL, 'Jerry Tiritilli', 2, 153, 'ODY'), 
('N', 'creature', '2N', 1, 2, 'Ray Lago', 0, 154, 'ODY'), 
('N', 'creature', '2NN', 1, 1, 'Pete Venters', 1, 155, 'ODY'), 
('N', 'enchantement', '3N',  NULL, NULL, 'Eric Peterson', 0, 156, 'ODY'), 
('N', 'creature', '3NN', 3, 3, 'Mark Tedin', 2, 157, 'ODY'), 
('N', 'creature', '1N', 3, 3, 'Kev Walker', 1, 158, 'ODY'), 
('N', 'creature', '3NN', 2, 2, 'Paolo Parente', 1, 159, 'ODY'), 
('N', 'enchantement', '3NN',  NULL, NULL, 'Jerry Tiritilli', 1, 160, 'ODY'), 
('N', 'ephemere', 'XN',  NULL, NULL, 'Bob Petillo', 1, 161, 'ODY'), 
('N', 'rituel', 'N',  NULL, NULL, 'Paolo Parente', 1, 162, 'ODY'), 
('N', 'creature', '4NN', 4, 4, 'Greg Staples', 2, 163, 'ODY'), 
('N', 'ephemere', '1N',  NULL, NULL, 'Adam Rex', 2, 164, 'ODY'), 
('N', 'rituel', 'N',  NULL, NULL, 'Arnie Swekel', 2, 165, 'ODY'), 
('N', 'enchantement', '3NN',  NULL, NULL, 'Dave Dorman', 2, 166, 'ODY'), 
('N', 'creature', '3N', 1, 1, 'Daren Bader', 0, 167, 'ODY'), 
('N', 'creature', '4N', 3, 2, 'Pete Venters', 0, 168, 'ODY'), 
('N', 'creature', 'N', 1, 1, 'Adam Rex', 0, 169, 'ODY'), 
('N', 'enchantement', '1N',  NULL, NULL, 'Thomas M. Baxa', 1, 170, 'ODY'), 
('N', 'rituel', '3N',  NULL, NULL, 'Mark Romanoski', 1, 171, 'ODY'), 
('R', 'rituel', '3R',  NULL, NULL, 'Mike Ploog', 0, 172, 'ODY'), 
('R', 'creature', '4R', 2, 2, 'Greg & Tim Hildebrandt', 0, 173, 'ODY'), 
('R', 'creature', '6RR', 6, 6, 'Mark Tedin', 2, 174, 'ODY'), 
('R', 'creature', '2R', 2, 1, 'Ron Spears', 0, 175, 'ODY'), 
('R', 'ephemere', '3R',  NULL, NULL, 'Gary Ruddell', 1, 176, 'ODY'), 
('R', 'enchantement', '1R',  NULL, NULL, 'Dave Dorman', 1, 177, 'ODY'), 
('R', 'ephemere', 'R',  NULL, NULL, 'rk post', 0, 178, 'ODY'), 
('R', 'creature', '3R', 1, 1, 'Greg & Tim Hildebrandt', 2, 179, 'ODY'), 
('R', 'enchantement', '3RR',  NULL, NULL, 'Ron Spencer', 2, 180, 'ODY'), 
('R', 'creature', '3R', 2, 2, 'Scott M. Fischer', 0, 181, 'ODY'), 
('R', 'enchantement', '2RR',  NULL, NULL, 'Mark Brill', 2, 182, 'ODY'), 
('R', 'rituel', '3R',  NULL, NULL, 'Gary Ruddell', 1, 183, 'ODY'), 
('R', 'ephemere', '2R',  NULL, NULL, 'Greg & Tim Hildebrandt', 0, 184, 'ODY'), 
('R', 'creature', 'R', 1, 1, 'Mike Ploog', 0, 185, 'ODY'), 
('R', 'creature', '2R', 2, 2, 'Ciruelo', 1, 186, 'ODY'), 
('R', 'enchantement', '1RR',  NULL, NULL, 'Matt Cavatto', 2, 187, 'ODY'), 
('R', 'creature', '4R', 4, 3, 'Mike Ploog', 1, 188, 'ODY'), 
('R', 'rituel', '3R',  NULL, NULL, 'Wayne England', 0, 189, 'ODY'), 
('R', 'creature', '2R', 3, 4, 'Wayne England', 0, 190, 'ODY'), 
('R', 'ephemere', 'R',  NULL, NULL, 'Marc Fishman', 1, 191, 'ODY'), 
('R', 'rituel', '4R',  NULL, NULL, 'Anthony S. Waters', 2, 192, 'ODY'), 
('R', 'rituel', 'R',  NULL, NULL, 'Ron Spencer', 0, 193, 'ODY'), 
('R', 'ephemere', '1R',  NULL, NULL, 'Ron Spencer', 0, 194, 'ODY'), 
('R', 'creature', '4R', 2, 3, 'Ron Spears', 1, 195, 'ODY'), 
('R', 'creature', '3R', 3, 1, 'Ben Thompson', 0, 196, 'ODY'), 
('R', 'enchantement', '2RR',  NULL, NULL, 'Dave Dorman', 2, 197, 'ODY'), 
('R', 'creature', '4RR', 6, 1, 'Kev Walker', 2, 198, 'ODY'), 
('R', 'enchantement', '1R',  NULL, NULL, 'Dave Dorman', 0, 199, 'ODY'), 
('R', 'rituel', '1R',  NULL, NULL, 'Rob Alexander', 1, 200, 'ODY'), 
('R', 'rituel', '4RR',  NULL, NULL, 'Greg Staples', 1, 201, 'ODY'), 
('R', 'creature', '1R', 2, 2, 'Ron Spencer', 0, 202, 'ODY'), 
('R', 'enchantement', '2R',  NULL, NULL, 'Glen Angus', 1, 203, 'ODY'), 
('R', 'creature', '2RR', -1, -1, 'Carl Critchlow', 2, 204, 'ODY'), 
('R', 'creature', '3R', 1, 1, 'Mark Brill', 2, 205, 'ODY'), 
('R', 'creature', '1R', 3, 3, 'Dave Dorman', 1, 206, 'ODY'), 
('R', 'ephemere', '1R',  NULL, NULL, 'Franz Vohwinkel', 2, 207, 'ODY'), 
('R', 'ephemere', '2R',  NULL, NULL, 'Gary Ruddell', 2, 208, 'ODY'), 
('R', 'enchantement', 'R',  NULL, NULL, 'Christopher Moeller', 2, 209, 'ODY'), 
('R', 'creature', 'R', 1, 1, 'Terese Nielson', 2, 210, 'ODY'), 
('R', 'creature', '3R', 2, 3, 'Glen Angus', 0, 211, 'ODY'), 
('R', 'creature', '1R', 1, 1, 'Tony Szczudlo', 2, 212, 'ODY'), 
('R', 'creature', '2R', 1, 1, 'Bob Petillo', 0, 213, 'ODY'), 
('R', 'enchantement', '2R',  NULL, NULL, 'Darrell Riche', 1, 214, 'ODY'), 
('R', 'rituel', 'R',  NULL, NULL, 'Scott M. Fischer', 0, 215, 'ODY'), 
('R', 'rituel', '1R',  NULL, NULL, 'Dave Dorman', 1, 216, 'ODY'), 
('R', 'ephemere', 'R',  NULL, NULL, 'Bradley Williams', 0, 217, 'ODY'), 
('R', 'creature', '3RR', 0, 0, 'Dave Dorman', 2, 218, 'ODY'), 
('R', 'rituel', '3R',  NULL, NULL, 'Don Hazeltine', 0, 219, 'ODY'), 
('R', 'rituel', '3R',  NULL, NULL, 'Greg Staples', 2, 220, 'ODY'), 
('R', 'rituel', '3RR',  NULL, NULL, 'Matt Cavatto', 1, 221, 'ODY'), 
('R', 'creature', 'R', 1, 1, 'Paolo Parente', 1, 222, 'ODY'), 
('R', 'enchantement', '1RR',  NULL, NULL, 'Anthony S. Waters', 1, 223, 'ODY'), 
('R', 'ephemere', '4R',  NULL, NULL, 'Franz Vohwinkel', 0, 224, 'ODY'), 
('R', 'rituel', '1R',  NULL, NULL, 'Ciruelo', 0, 225, 'ODY'), 
('R', 'rituel', '1R',  NULL, NULL, 'Matt Cavatto', 1, 226, 'ODY'), 
('R', 'rituel', '8R',  NULL, NULL, 'Tony Szczudlo', 2, 227, 'ODY'), 
('R', 'creature', '2RR', 1, 1, 'Ron Spencer', 1, 228, 'ODY'), 
('V', 'enchantement', '1VV',  NULL, NULL, 'Heather Hudson', 2, 229, 'ODY'), 
('V', 'ephemere', '2VVV',  NULL, NULL, 'Ciruelo', 1, 230, 'ODY'), 
('V', 'rituel', '2V',  NULL, NULL, 'Carl Critchlow', 2, 231, 'ODY'), 
('V', 'creature', '2V', 2, 2, 'Donato Giancola', 0, 232, 'ODY'), 
('V', 'rituel', 'V',  NULL, NULL, 'Jim Nelson', 0, 233, 'ODY'), 
('V', 'creature', 'VVV', 1, 1, 'John Avon', 2, 234, 'ODY'), 
('V', 'creature', '4VV', 3, 4, 'Eric Peterson', 1, 235, 'ODY'), 
('V', 'rituel', '2V',  NULL, NULL, 'Jeff Remmer', 1, 236, 'ODY'), 
('V', 'creature', 'V', 1, 1, 'Gary Ruddell', 0, 237, 'ODY'), 
('V', 'creature', 'V', 1, 1, 'Mark Zug', 0, 238, 'ODY'), 
('V', 'enchantement', '1V',  NULL, NULL, 'Greg & Tim Hildebrandt', 1, 239, 'ODY'), 
('V', 'ephemere', '2VV',  NULL, NULL, 'Anthony S. Waters', 0, 240, 'ODY'), 
('V', 'creature', '3VV', 4, 4, 'Heather Hudson', 1, 241, 'ODY'), 
('V', 'enchantement', '1V',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 242, 'ODY'), 
('V', 'enchantement', '1VV',  NULL, NULL, 'Rebecca Guay', 2, 243, 'ODY'), 
('V', 'ephemere', '1V',  NULL, NULL, 'Greg Staples', 1, 244, 'ODY'), 
('V', 'creature', 'XV', 0, 0, 'Ron Spencer', 2, 245, 'ODY'), 
('V', 'creature', '3V', 2, 3, 'Ron Spears', 0, 246, 'ODY'), 
('V', 'creature', '2V', 3, 1, 'D. Alexander Gregory', 0, 247, 'ODY'), 
('V', 'creature', '3V', 1, 1, 'Kev Walker', 2, 248, 'ODY'), 
('V', 'creature', '1VV', 2, 2, 'Greg & Tim Hildebrandt', 0, 249, 'ODY'), 
('V', 'creature', '3VV', 3, 3, 'Thomas M. Baxa', 1, 250, 'ODY'), 
('V', 'ephemere', '1V',  NULL, NULL, 'Rebecca Guay', 0, 251, 'ODY'), 
('V', 'ephemere', '1V',  NULL, NULL, 'Gary Ruddell', 0, 252, 'ODY'), 
('V', 'creature', '3V', 2, 2, 'Justin Sweet', 0, 253, 'ODY'), 
('V', 'creature', '2V', 1, 2, 'Daren Bader', 1, 254, 'ODY'), 
('V', 'creature', '2V', 1, 1, 'John Matson', 2, 255, 'ODY'), 
('V', 'enchantement', '1VV',  NULL, NULL, 'Rebecca Guay', 2, 256, 'ODY'), 
('V', 'rituel', 'XV',  NULL, NULL, 'Ron Spencer', 2, 257, 'ODY'), 
('V', 'creature', 'V', 1, 1, 'Terese Nielson', 1, 258, 'ODY'), 
('V', 'creature', '5V', 1, 1, 'Christopher Moeller', 2, 259, 'ODY'), 
('V', 'rituel', '2VVV',  NULL, NULL, 'Carl Critchlow', 1, 260, 'ODY'), 
('V', 'rituel', 'V',  NULL, NULL, 'Greg & Tim Hildebrandt', 1, 261, 'ODY'), 
('V', 'enchantement', 'V',  NULL, NULL, 'Alex Horley', 0, 262, 'ODY'), 
('V', 'creature', '4V', 3, 4, 'Dave Dorman', 0, 263, 'ODY'), 
('V', 'ephemere', '2V',  NULL, NULL, 'Keith Garletts', 0, 264, 'ODY'), 
('V', 'rituel', '1V',  NULL, NULL, 'Bradley Williams', 0, 265, 'ODY'), 
('V', 'rituel', '6V',  NULL, NULL, 'Kev Walker', 1, 266, 'ODY'), 
('V', 'creature', 'VVV', 2, 2, 'Greg Staples', 2, 267, 'ODY'), 
('V', 'enchantement', '2V',  NULL, NULL, 'Ciruelo', 0, 268, 'ODY'), 
('V', 'rituel', 'V',  NULL, NULL, 'Greg & Tim Hildebrandt', 0, 269, 'ODY'), 
('V', 'creature', '1V', 1, 2, 'Jerry Tiritilli', 1, 270, 'ODY'), 
('V', 'creature', '2V', 3, 2, 'Rick Farrell', 2, 271, 'ODY'), 
('V', 'creature', '3V', 3, 3, 'Arnie Swekel', 0, 272, 'ODY'), 
('V', 'creature', '1VV', 2, 2, 'Carl Critchlow', 2, 273, 'ODY'), 
('V', 'enchantement', '1VV',  NULL, NULL, 'Anthony S. Waters', 1, 274, 'ODY'), 
('V', 'enchantement', '1VV',  NULL, NULL, 'Matt Cavatto', 1, 275, 'ODY'), 
('V', 'creature', '4VVV', 4, 5, 'Wayne England', 2, 276, 'ODY'), 
('V', 'ephemere', '1V',  NULL, NULL, 'Arnie Swekel', 1, 277, 'ODY'), 
('V', 'creature', '1VV', -1, -1, 'Jim Nelson', 2, 278, 'ODY'), 
('V', 'creature', '2V', 2, 2, 'Carl Critchlow', 1, 279, 'ODY'), 
('V', 'enchantement', '4V',  NULL, NULL, 'Edward P. Beard, Jr.', 2, 280, 'ODY'), 
('V', 'ephemere', '2V',  NULL, NULL, 'Greg Staples', 1, 281, 'ODY'), 
('V', 'creature', '1V', 1, 1, 'Carl Critchlow', 0, 282, 'ODY'), 
('V', 'creature', '1V', 2, 2, 'Anthony S. Waters', 0, 283, 'ODY'), 
('V', 'creature', 'V', 1, 2, 'Rick Farrell', 0, 284, 'ODY'), 
('V', 'creature', '3V', 1, 2, 'Alex Horley', 2, 285, 'ODY'), 
('M', 'creature', 'WBNRV', 5, 5, 'Ron Spears', 2, 286, 'ODY'), 
('M', 'rituel', '2RV',  NULL, NULL, 'Alex Horley', 2, 287, 'ODY'), 
('M', 'creature', '5WB', 4, 4, 'Matt Cavatto', 2, 288, 'ODY'), 
('M', 'creature', '1RV', 1, 2, 'Franz Vohwinkel', 1, 289, 'ODY'), 
('M', 'creature', '2VW', 3, 3, 'Gary Ruddell', 2, 290, 'ODY'), 
('M', 'creature', '1WB', 1, 2, 'Glen Angus', 1, 291, 'ODY'), 
('M', 'creature', '1BN', 1, 2, 'Edward P. Beard, Jr.', 1, 292, 'ODY'), 
('M', 'creature', '1NR', 1, 2, 'Mark Brill', 1, 293, 'ODY'), 
('M', 'creature', '1BN', 1, 3, 'Rick Farrell', 2, 294, 'ODY'), 
('M', 'creature', '1VW', 1, 2, 'Monte Michael Moore', 1, 295, 'ODY'), 
('M', 'creature', '6NR', 5, 5, 'Gary Ruddell', 2, 296, 'ODY'), 
('I', 'artefact', '2',  NULL, NULL, 'Tony Szczudlo', 2, 297, 'ODY'), 
('I', 'artefact', '4',  NULL, NULL, 'Anthony S. Waters', 2, 298, 'ODY'), 
('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 299, 'ODY'), 
('I', 'creature', '4', 0, 0, 'Brian Snoddy', 2, 300, 'ODY'), 
('I', 'creature', '6', 3, 4, 'Mark Tedin', 1, 301, 'ODY'), 
('I', 'creature', '2', 0, 1, 'Alex Horley', 1, 302, 'ODY'), 
('I', 'creature', '5',  NULL, NULL, 'Donato Giancola', 2, 303, 'ODY'), 
('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 304, 'ODY'), 
('I', 'creature', '4', 2, 3, 'Brian Snoddy', 2, 305, 'ODY'), 
('I', 'creature', '3', 2, 1, 'Jerry Tiritilli', 1, 306, 'ODY'), 
('I', 'artefact', '3',  NULL, NULL, 'Jim Nelson', 1, 307, 'ODY'), 
('I', 'artefact', '4',  NULL, NULL, 'David Martin', 1, 308, 'ODY'), 
('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 309, 'ODY'), 
('I', 'artefact', '2',  NULL, NULL, 'Jim Nelson', 1, 310, 'ODY'), 
('I', 'artefact', '1',  NULL, NULL, 'David Martin', 1, 311, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Edward P. Beard, Jr.', 0, 312, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 313, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Brian Snoddy', 0, 314, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 315, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 316, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 1, 317, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 2, 318, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Monte Michael Moore', 2, 319, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 2, 320, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'John Avon', 2, 321, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 1, 322, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Glen Angus', 2, 323, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 0, 324, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 325, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Glen Angus', 2, 326, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 2, 327, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Ron Spencer', 2, 328, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'David Martin', 2, 329, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 330, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 331, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Don Hazeltine', 0, 332, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Eric Peterson', 0, 333, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 334, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 335, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Ben Thompson', 0, 336, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 337, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 338, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Jerry Tiritilli', 0, 339, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Arnie Swekel', 0, 340, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 341, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Alan Pollack', 0, 342, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Anthony S. Waters', 0, 343, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Franz Vohwinkel', 0, 344, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 345, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Tony Szczudlo', 0, 346, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Larry Elmore', 0, 347, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Rob Alexander', 0, 348, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Jerry Tiritilli', 0, 349, 'ODY'), 
('T', 'terrain', 'T',  NULL, NULL, 'Tony Szczudlo', 0, 350, 'ODY'), 
--Insert into carte_virtuelle Values 
('W', 'creature', '6W', 5, 5, 'rk post', 2, 1, 'TOR'), 
('W', 'creature', '3W', 1, 1, 'Greg Staples', 0, 2, 'TOR'), 
('W', 'rituel', '1WW', NULL, NULL, 'Ron Spears', 1, 3, 'TOR'), 
('W', 'ephemere', '1W', NULL, NULL, 'Greg & Tim Hildebrandt', 1, 4, 'TOR'), 
('W', 'enchantement', '2W', NULL, NULL, 'Keith Garletts', 0, 5, 'TOR'), 
('W', 'ephemere', '2W', NULL, NULL, 'Mark Brill', 0, 6, 'TOR'), 
('W', 'enchantement', '1W', NULL, NULL, 'Christopher Moeller', 1, 7, 'TOR'), 
('W', 'creature', '3W', 2, 3, 'Daren Bader', 2, 8, 'TOR'), 
('W', 'creature', '1WW', 2, 1, 'Mark Brill', 0, 9, 'TOR'), 
('W', 'rituel', '1W', NULL, NULL, 'Tony Szczudlo', 2, 10, 'TOR'), 
('W', 'creature', '1W', 1, 2, 'Edward P. Beard, Jr.', 0, 11, 'TOR'), 
('W', 'ephemere', 'W', NULL, NULL, 'Adam Rex', 0, 12, 'TOR'), 
('W', 'creature', '2WW', 3, 3, 'Eric Peterson', 2, 13, 'TOR'), 
('W', 'creature', '2W', 2, 2, 'Gary Ruddell', 2, 14, 'TOR'), 
('W', 'ephemere', '3W', NULL, NULL, 'rk post', 0, 15, 'TOR'), 
('W', 'creature', '2W', 2, 2, 'Matt Cavotta', 1, 16, 'TOR'), 
('W', 'enchantement', '1W', NULL, NULL, 'Jerry Tiritilli', 1, 17, 'TOR'), 
('W', 'creature', '3W', 1, 4, 'Greg & Tim Hildebrandt', 0, 18, 'TOR'), 
('W', 'creature', '3W', 2, 3, 'Greg & Tim Hildebrandt', 1, 19, 'TOR'), 
('W', 'enchantement', '3WWW', NULL, NULL, 'Rebecca Guay', 2, 20, 'TOR'), 
('W', 'ephemere', 'WW', NULL, NULL, 'Mark Tedin', 2, 21, 'TOR'), 
('B', 'ephemere', '1B', NULL, NULL, 'Justin Sweet', 2, 22, 'TOR'), 
('B', 'creature', '1BB', 1, 3, 'Eric Peterson', 2, 23, 'TOR'), 
('B', 'creature', '1B', 1, 3, 'Arnie Swekel', 0, 24, 'TOR'), 
('B', 'creature', '3B', 2, 2, 'DiTerlizzi', 1, 25, 'TOR'), 
('B', 'rituel', 'XB', NULL, NULL, 'Gary Ruddell', 1, 26, 'TOR'), 
('B', 'creature', '4B', 3, 3, 'Rob Alexander', 0, 27, 'TOR'), 
('B', 'creature', '1B', 1, 1, 'Pete Venters', 1, 28, 'TOR'), 
('B', 'creature', '3B', 2, 3, 'Keith Garletts', 1, 29, 'TOR'), 
('B', 'creature', '1B', 1, 1, 'Jerry Tiritilli', 0, 30, 'TOR'), 
('B', 'creature', '1B', 1, 1, 'Alex Horley', 2, 31, 'TOR'), 
('B', 'rituel', '3B', NULL, NULL, 'Thomas M. Baxa', 0, 32, 'TOR'), 
('B', 'ephemere', '2B', NULL, NULL, 'Anthony S. Waters', 1, 33, 'TOR'), 
('B', 'enchantement', '1B', NULL, NULL, 'Christopher Moeller', 1, 34, 'TOR'), 
('B', 'enchantement', 'B', NULL, NULL, 'Roger Raupp', 0, 35, 'TOR'), 
('B', 'rituel', '3B', NULL, NULL, 'Daren Bader', 0, 36, 'TOR'), 
('B', 'ephemere', '1B', NULL, NULL, 'Ron Spencer', 2, 37, 'TOR'), 
('B', 'enchantement', '1B', NULL, NULL, 'David Martin', 0, 38, 'TOR'), 
('B', 'creature', '2B', 2, 2, 'Glen Angus', 0, 39, 'TOR'), 
('B', 'creature', '3BB', 3, 3, 'Arnie Swekel', 1, 40, 'TOR'), 
('B', 'ephemere', '2B', NULL, NULL, 'Ron Spencer', 0, 41, 'TOR'), 
('B', 'creature', '3B', 2, 3, 'Mark Zug', 2, 42, 'TOR'), 
('B', 'ephemere', 'B', NULL, NULL, 'Jim Nelson', 0, 43, 'TOR'), 
('B', 'ephemere', '3B', NULL, NULL, 'Ben Thompson', 2, 44, 'TOR'), 
('B', 'creature', '2BB', 3, 3, 'Scott M. Fischer', 2, 45, 'TOR'), 
('B', 'rituel', 'B', NULL, NULL, 'Greg Staples', 2, 46, 'TOR'), 
('B', 'creature', '2B', 2, 1, 'Matt Cavotta', 0, 47, 'TOR'), 
('B', 'enchantement', '1B', NULL, NULL, 'Bradley Williams', 1, 48, 'TOR'), 
('B', 'rituel', 'BB', NULL, NULL, 'Wayne England', 2, 49, 'TOR'), 
('N', 'creature', '1N', 1, 1, 'Ron Spencer', 1, 50, 'TOR'), 
('N', 'ephemere', '1N', NULL, NULL, 'Greg & Tim Hildebrandt', 0, 51, 'TOR'), 
('N', 'creature', '2NN', 2, 1, 'Donato Giancola', 0, 52, 'TOR'), 
('N', 'creature', '1NN', 1, 1, 'Pete Venters', 0, 53, 'TOR'), 
('N', 'creature', 'N', 2, 1, 'Edward P. Beard, Jr.', 0, 54, 'TOR'), 
('N', 'creature', '3NN', 6, 5, 'Glen Angus', 1, 55, 'TOR'), 
('N', 'creature', '3NN', 3, 3, 'Mark Zug', 2, 56, 'TOR'), 
('N', 'rituel', '1N', NULL, NULL, 'Ben Thompson', 1, 57, 'TOR'), 
('N', 'rituel', '1NN', NULL, NULL, 'Heather Hudson', 0, 58, 'TOR'), 
('N', 'enchantement', '2NNN', NULL, NULL, 'Pete Venters', 2, 59, 'TOR'), 
('N', 'creature', '2NN', 2, 3, 'Daren Bader', 0, 60, 'TOR'), 
('N', 'creature', '3N', 2, 2, 'Adam Rex', 1, 61, 'TOR'), 
('N', 'creature', '2N', 2, 2, 'Daren Bader', 0, 62, 'TOR'), 
('N', 'creature', '4N', 3, 3, 'Terese Nielsen', 1, 63, 'TOR'), 
('N', 'creature', '8NNN', 8, 8, 'Greg Staples', 2, 64, 'TOR'), 
('N', 'creature', '3N', 3, 1, 'rk post', 2, 65, 'TOR'), 
('N', 'ephemere', '3N', NULL, NULL, 'John Avon', 2, 66, 'TOR'), 
('N', 'creature', '4NN', 6, 3, 'Greg Staples', 2, 67, 'TOR'), 
('N', 'enchantement', '2NN', NULL, NULL, 'John Matson', 2, 68, 'TOR'), 
('N', 'creature', '1N', 1, 1, 'Dana Knutson', 0, 69, 'TOR'), 
('N', 'rituel', '4N', NULL, NULL, 'Eric Peterson', 1, 70, 'TOR'), 
('N', 'enchantement', '2NN', NULL, NULL, 'Mike Ploog', 2, 71, 'TOR'), 
('N', 'enchantement', '1NN', NULL, NULL, 'Christopher Moeller', 1, 72, 'TOR'), 
('N', 'rituel', '2NN', NULL, NULL, 'Eric Peterson', 2, 73, 'TOR'), 
('N', 'creature', 'NN', 2, 1, 'Brian Snoddy', 2, 74, 'TOR'), 
('N', 'creature', '2N', 3, 1, 'Adam Rex', 0, 75, 'TOR'), 
('N', 'ephemere', '2NN', NULL, NULL, 'Alex Horley', 0, 76, 'TOR'), 
('N', 'creature', 'N', 1, 1, 'Wayne England', 0, 77, 'TOR'), 
('N', 'rituel', '1NN', NULL, NULL, 'Ciruelo', 0, 78, 'TOR'), 
('N', 'rituel', 'N', NULL, NULL, 'John Matson', 0, 79, 'TOR'), 
('N', 'creature', '3NN', 4, 4, 'Kev Walker', 2, 80, 'TOR'), 
('N', 'enchantement', '1NN', NULL, NULL, 'Clyde Caldwell', 0, 81, 'TOR'), 
('N', 'creature', '1NNN', 3, 3, 'Arnie Swekel', 2, 82, 'TOR'), 
('N', 'rituel', '1N', NULL, NULL, 'Scott M. Fischer', 1, 83, 'TOR'), 
('N', 'creature', '1NN', 1, 1, 'John Avon', 1, 84, 'TOR'), 
('N', 'creature', '4N', 3, 2, 'Carl Critchlow', 0, 85, 'TOR'), 
('N', 'enchantement', '1N', NULL, NULL, 'Greg & Tim Hildebrandt', 1, 86, 'TOR'), 
('N', 'rituel', '2N', NULL, NULL, 'Keith Garletts', 0, 87, 'TOR'), 
('N', 'ephemere', '4N', NULL, NULL, 'Alan Pollack', 0, 88, 'TOR'), 
('N', 'creature', 'NNN', 2, 2, 'Brian Snoddy', 1, 89, 'TOR'), 
('R', 'ephemere', '1R', NULL, NULL, 'Gary Ruddell', 0, 90, 'TOR'), 
('R', 'creature', '1RR', 2, 2, 'Ron Spears', 2, 91, 'TOR'), 
('R', 'creature', '1R', 2, 2, 'Mark Tedin', 0, 92, 'TOR'), 
('R', 'enchantement', 'R', NULL, NULL, 'Mike Ploog', 0, 93, 'TOR'), 
('R', 'creature', '5RR', 4, 4, 'Ron Spears', 1, 94, 'TOR'), 
('R', 'rituel', 'RR', NULL, NULL, 'Tony Szczudlo', 2, 95, 'TOR'), 
('R', 'creature', 'R', 1, 1, 'Terese Nielsen', 0, 96, 'TOR'), 
('R', 'ephemere', '1RR', NULL, NULL, 'Greg & Tim Hildebrandt', 0, 97, 'TOR'), 
('R', 'ephemere', 'XR', NULL, NULL, 'Donato Giancola', 1, 98, 'TOR'), 
('R', 'rituel', '1R', NULL, NULL, 'Carl Critchlow', 0, 99, 'TOR'), 
('R', 'creature', 'R', 1, 1, 'Jim Nelson', 2, 100, 'TOR'), 
('R', 'creature', '1RR', 2, 2, 'Mike Ploog', 2, 101, 'TOR'), 
('R', 'rituel', '5RR', NULL, NULL, 'Don Hazeltine', 0, 102, 'TOR'), 
('R', 'creature', '2R', 3, 2, 'Glen Angus', 0, 103, 'TOR'), 
('R', 'rituel', 'R', NULL, NULL, 'Anthony S. Waters', 2, 104, 'TOR'), 
('R', 'creature', '2RR', 3, 3, 'rk post', 1, 105, 'TOR'), 
('R', 'creature', '3R', 2, 2, 'Pete Venters', 1, 106, 'TOR'), 
('R', 'creature', '4R', 3, 2, 'Justin Sweet', 0, 107, 'TOR'), 
('R', 'creature', '6RR', 5, 6, 'Jim Nelson', 2, 108, 'TOR'), 
('R', 'creature', '3R', 2, 2, 'Wayne England', 0, 109, 'TOR'), 
('R', 'creature', '2R', 2, 5, 'David Martin', 1, 110, 'TOR'), 
('R', 'creature', '2RR', 3, 3, 'Scott M. Fischer', 2, 111, 'TOR'), 
('R', 'enchantement', '2R', NULL, NULL, 'Christopher Moeller', 1, 112, 'TOR'), 
('R', 'ephemere', '3RR', NULL, NULL, 'Carl Critchlow', 2, 113, 'TOR'), 
('R', 'rituel', 'RR', NULL, NULL, 'Bradley Williams', 2, 114, 'TOR'), 
('R', 'ephemere', 'R', NULL, NULL, 'Terese Nielsen', 0, 115, 'TOR'), 
('R', 'ephemere', '3R', NULL, NULL, 'Mark Romanoski', 1, 116, 'TOR'), 
('R', 'ephemere', '1RRR', NULL, NULL, 'Bob Petillo', 1, 117, 'TOR'), 
('V', 'rituel', '3V', NULL, NULL, 'Edward P. Beard, Jr.', 0, 118, 'TOR'), 
('V', 'creature', '2V', 3, 3, 'Bob Petillo', 1, 119, 'TOR'), 
('V', 'creature', '3VV', 4, 4, 'John Avon', 1, 120, 'TOR'), 
('V', 'creature', 'V', 1, 1, 'Heather Hudson', 0, 121, 'TOR'), 
('V', 'creature', '3V', 3, 3, 'Justin Sweet', 1, 122, 'TOR'), 
('V', 'creature', '5V', 3, 3, 'Mark Zug', 0, 123, 'TOR'), 
('V', 'rituel', 'V', NULL, NULL, 'Rebecca Guay', 1, 124, 'TOR'), 
('V', 'rituel', '2V', NULL, NULL, 'Darrell Riche', 0, 125, 'TOR'), 
('V', 'creature', '3VV', 6, 8, 'Scott M. Fischer', 2, 126, 'TOR'), 
('V', 'rituel', 'V', NULL, NULL, 'Franz Vohwinkel', 2, 127, 'TOR'), 
('V', 'rituel', '2VV', NULL, NULL, 'Rebecca Guay', 0, 128, 'TOR'), 
('V', 'creature', '3V', 2, 2, 'Jim Nelson', 0, 129, 'TOR'), 
('V', 'creature', '2V', 1, 2, 'Clyde Caldwell', 0, 130, 'TOR'), 
('V', 'creature', '2V', 2, 2, 'Matt Cavotta', 2, 131, 'TOR'), 
('V', 'creature', '2VV', 2, 3, 'Mark Romanoski', 0, 132, 'TOR'), 
('V', 'creature', '3V', 2, 2, 'Darrell Riche', 2, 133, 'TOR'), 
('V', 'enchantement', '2V', NULL, NULL, 'Christopher Moeller', 1, 134, 'TOR'), 
('V', 'rituel', 'VV', NULL, NULL, 'Darrell Riche', 2, 135, 'TOR'), 
('V', 'rituel', '3VV', NULL, NULL, 'Matt Cavotta', 2, 136, 'TOR'), 
('V', 'creature', '2VV', 3, 3, 'Alex Horley', 2, 137, 'TOR'), 
('V', 'creature', '1V', 2, 1, 'Mark Romanoski', 1, 138, 'TOR'), 
('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 139, 'TOR'), 
('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 140, 'TOR'), 
('T', 'terrain', 'T', NULL, NULL, 'Alan Pollack', 1, 141, 'TOR'), 
('T', 'terrain', 'T', NULL, NULL, 'Tony Szczudlo', 1, 142, 'TOR'), 
('T', 'terrain', 'T', NULL, NULL, 'Rob Alexander', 1, 143, 'TOR'), 
--Insert into carte_virtuelle Values 
('W', 'creature', '5WW', 4, 4, 'Pete Venters', 1, 1, 'JUD'), 
('W', 'ephemere', '2W', NULL, NULL, 'Roger Raupp', 1, 2, 'JUD'), 
('W', 'rituel', '2WW', NULL, NULL, 'Randy Gallegos', 1, 3, 'JUD'), 
('W', 'creature', '3W', 2, 2, 'Wayne England', 0, 4, 'JUD'), 
('W', 'creature', 'W', 1, 1, 'Roger Raupp', 0, 5, 'JUD'), 
('W', 'creature', '4W', 1, 6, 'Roger Raupp', 0, 6, 'JUD'), 
('W', 'enchantement', '1W', NULL, NULL, 'Scott M. Fischer', 0, 7, 'JUD'), 
('W', 'ephemere', '3W', NULL, NULL, 'Carl Critchlow', 1, 8, 'JUD'), 
('W', 'creature', '2WW', 2, 4, 'Rebecca Guay', 2, 9, 'JUD'), 
('W', 'ephemere', 'W', NULL, NULL, 'Carl Critchlow', 0, 10, 'JUD'), 
('W', 'creature', '3WW', 3, 3, 'Donato Giancola', 2, 11, 'JUD'), 
('W', 'rituel', '3WW', NULL, NULL, 'Alan Pollack', 2, 12, 'JUD'), 
('W', 'ephemere', '1W', NULL, NULL, 'Dave Dorman', 0, 13, 'JUD'), 
('W', 'ephemere', '1W', NULL, NULL, 'Adam Rex', 0, 14, 'JUD'), 
('W', 'creature', '2W', 2, 2, 'Eric Peterson', 2, 15, 'JUD'), 
('W', 'creature', '3WW', 0, 0, 'David Martin', 1, 16, 'JUD'), 
('W', 'creature', '1W', 0, 0, 'Jim Nelson', 0, 17, 'JUD'), 
('W', 'ephemere', '2W', NULL, NULL, 'Eric Peterson', 0, 18, 'JUD'), 
('W', 'creature', '2W', 1, 3, 'Jeff Easley', 2, 19, 'JUD'), 
('W', 'ephemere', '1W', NULL, NULL, 'Doug Chaffee', 0, 20, 'JUD'), 
('W', 'creature', '3WW', 3, 4, 'Christopher Moeller', 2, 21, 'JUD'), 
('W', 'creature', '2W', 1, 3, 'Christopher Moeller', 0, 22, 'JUD'), 
('W', 'creature', '5WWW', 6, 6, 'Matthew D. Wilson', 2, 23, 'JUD'), 
('W', 'enchantement', '2W', NULL, NULL, 'Scott M. Fischer', 2, 24, 'JUD'), 
('W', 'enchantement', '1W', NULL, NULL, 'Rob Alexander', 1, 25, 'JUD'), 
('W', 'enchantement', '2W', NULL, NULL, 'Gary Ruddell', 1, 26, 'JUD'), 
('W', 'creature', 'W', 1, 1, 'Ron Spears', 1, 27, 'JUD'), 
('W', 'creature', 'W', 1, 1, 'Heather Hudson', 0, 28, 'JUD'), 
('W', 'enchantement', '2WW', NULL, NULL, 'Mike Ploog', 2, 29, 'JUD'), 
('W', 'creature', '1W', 1, 1, 'John Matson', 0, 30, 'JUD'), 
('W', 'enchantement', '2W', NULL, NULL, 'Alex Horley', 1, 31, 'JUD'), 
('W', 'creature', '3W', 2, 2, 'Kev Walker', 1, 32, 'JUD'), 
('W', 'creature', '1WW', 2, 2, 'Eric Peterson', 0, 33, 'JUD'), 
('B', 'creature', '3B', 2, 1, 'Edward P. Beard, Jr.', 0, 34, 'JUD'), 
('B', 'creature', '1BB', 1, 1, 'Alan Pollack', 2, 35, 'JUD'), 
('B', 'creature', '2B', 2, 1, 'Tony Szczudlo', 1, 36, 'JUD'), 
('B', 'ephemere', '2B', NULL, NULL, 'Jim Nelson', 2, 37, 'JUD'), 
('B', 'ephemere', 'B', NULL, NULL, 'Ben Thompson', 0, 38, 'JUD'), 
('B', 'ephemere', 'B', NULL, NULL, 'Don Hazeltine', 0, 39, 'JUD'), 
('B', 'ephemere', 'X1B', NULL, NULL, 'Ben Thompson', 1, 40, 'JUD'), 
('B', 'ephemere', '1B', NULL, NULL, 'Bradley Williams', 0, 41, 'JUD'), 
('B', 'creature', 'B', 1, 1, 'Ron Spears', 0, 42, 'JUD'), 
('B', 'ephemere', '2B', NULL, NULL, 'Fred Rahmqvist', 0, 43, 'JUD'), 
('B', 'ephemere', '1B', NULL, NULL, 'Pete Venters', 1, 44, 'JUD'), 
('B', 'enchantement', '1B', NULL, NULL, 'Ben Thompson', 0, 45, 'JUD'), 
('B', 'ephemere', 'B', NULL, NULL, 'Bradley Williams', 0, 46, 'JUD'), 
('B', 'creature', '3B', 3, 4, 'Mark Brill', 0, 47, 'JUD'), 
('B', 'enchantement', '3BB', NULL, NULL, 'Mike Ploog', 2, 48, 'JUD'), 
('B', 'rituel', '1B', NULL, NULL, 'John Avon', 1, 49, 'JUD'), 
('B', 'creature', '4B', 1, 5, 'Mark Tedin', 2, 50, 'JUD'), 
('B', 'ephemere', '3BBB', NULL, NULL, 'Pete Venters', 2, 51, 'JUD'), 
('B', 'enchantement', '2BBB', NULL, NULL, 'Jim Nelson', 2, 52, 'JUD'), 
('B', 'enchantement', '2B', NULL, NULL, 'Don Hazeltine', 1, 53, 'JUD'), 
('B', 'creature', '3B', 2, 2, 'Rebecca Guay', 1, 54, 'JUD'), 
('B', 'creature', '3BB', 5, 5, 'Heather Hudson', 2, 55, 'JUD'), 
('B', 'creature', '3B', 3, 6, 'Glen Angus', 1, 56, 'JUD'), 
('B', 'creature', '2B', 3, 4, 'Thomas M. Baxa', 0, 57, 'JUD'), 
('B', 'creature', '5BB', 6, 1, 'Heather Hudson', 2, 58, 'JUD'), 
('B', 'creature', '1B', 2, 2, 'Doug Chaffee', 0, 59, 'JUD'), 
('B', 'creature', '2B', 2, 4, 'John Avon', 1, 60, 'JUD'), 
('N', 'creature', '2NN', 2, 2, 'Carl Critchlow', 2, 61, 'JUD'), 
('N', 'rituel', 'N', NULL, NULL, 'Ron Spencer', 1, 62, 'JUD'), 
('N', 'creature', 'N', 1, 1, 'Pete Venters', 0, 63, 'JUD'), 
('N', 'rituel', '1NN', NULL, NULL, 'Jeff Easley', 2, 64, 'JUD'), 
('N', 'creature', '3N', 2, 1, 'Heather Hudson', 0, 65, 'JUD'), 
('N', 'creature', '3N', 2, 2, 'Thomas M. Baxa', 1, 66, 'JUD'), 
('N', 'ephemere', '1N', NULL, NULL, 'Tim Hildebrandt', 1, 67, 'JUD'), 
('N', 'creature', '3NN', 0, 4, 'Mark Tedin', 2, 68, 'JUD'), 
('N', 'creature', '4N', 5, 5, 'Matthew D. Wilson', 2, 69, 'JUD'), 
('N', 'rituel', '5NN', NULL, NULL, 'Jerry Tiritilli', 2, 70, 'JUD'), 
('N', 'rituel', 'XN', NULL, NULL, 'Bob Petillo', 0, 71, 'JUD'), 
('N', 'rituel', 'NN', NULL, NULL, 'Arnie Swekel', 1, 72, 'JUD'), 
('N', 'creature', '4NNN', -1, -1, 'Carl Critchlow', 2, 73, 'JUD'), 
('N', 'ephemere', '1N', NULL, NULL, 'Bradley Williams', 0, 74, 'JUD'), 
('N', 'creature', '4N', 4, 4, 'Kev Walker', 1, 75, 'JUD'), 
('N', 'creature', '2N', 2, 2, 'Mark Tedin', 0, 76, 'JUD'), 
('R', 'creature', '3R', 2, 2, 'John Avon', 1, 77, 'JUD'), 
('R', 'enchantement', '2R', NULL, NULL, 'Mark Brill', 0, 78, 'JUD'), 
('R', 'creature', '2R', 2, 2, 'Mike Ploog', 0, 79, 'JUD'), 
('R', 'rituel', '1R', NULL, NULL, 'Dave Dorman', 0, 80, 'JUD'), 
('R', 'rituel', '1RR', NULL, NULL, 'Matthew D. Wilson', 2, 81, 'JUD'), 
('R', 'rituel', '2R', NULL, NULL, 'Mark Tedin', 1, 82, 'JUD'), 
('R', 'rituel', '1R', NULL, NULL, 'Scott M. Fischer', 2, 83, 'JUD'), 
('R', 'creature', 'RRR', 2, 2, 'Arnie Swekel', 2, 84, 'JUD'), 
('R', 'creature', '3R', 2, 2, 'Edward P. Beard, Jr.', 1, 85, 'JUD'), 
('R', 'creature', 'R', 1, 1, 'Thomas M. Baxa', 0, 86, 'JUD'), 
('R', 'ephemere', '6R', NULL, NULL, 'Alan Pollack', 0, 87, 'JUD'), 
('R', 'rituel', 'XRR', NULL, NULL, 'David Martin', 1, 88, 'JUD'), 
('R', 'ephemere', '1R', NULL, NULL, 'Glen Angus', 0, 89, 'JUD'), 
('R', 'creature', '2RR', 2, 2, 'Greg Staples', 2, 90, 'JUD'), 
('R', 'creature', '5R', 2, 2, 'Keith Garletts', 0, 91, 'JUD'), 
('R', 'enchantement', '1R', NULL, NULL, 'Christopher Moeller', 1, 92, 'JUD'), 
('R', 'creature', '2RR', 3, 1, 'rk post', 2, 93, 'JUD'), 
('R', 'ephemere', 'R', NULL, NULL, 'Darrell Riche', 0, 94, 'JUD'), 
('R', 'creature', 'R', 1, 1, 'Greg Hildebrandt', 0, 95, 'JUD'), 
('R', 'rituel', '3RR', NULL, NULL, 'Ron Spears', 2, 96, 'JUD'), 
('R', 'enchantement', '2R', NULL, NULL, 'Ron Spencer', 1, 97, 'JUD'), 
('R', 'ephemere', '2R', NULL, NULL, 'Greg Hildebrandt', 2, 98, 'JUD'), 
('R', 'creature', '3RR', 6, 6, 'John Matson', 1, 99, 'JUD'), 
('R', 'creature', '3R', 3, 1, 'Mark Romanoski', 0, 100, 'JUD'), 
('R', 'rituel', '3R', NULL, NULL, 'Ben Thompson', 1, 101, 'JUD'), 
('R', 'rituel', '3R', NULL, NULL, 'Tony Szczudlo', 0, 102, 'JUD'), 
('R', 'creature', '3RRR', 7, 7, 'Wayne England', 2, 103, 'JUD'), 
('V', 'creature', '1VV', 2, 2, 'Randy Gallegos', 0, 104, 'JUD'), 
('V', 'creature', '2V', 1, 4, 'John Matson', 1, 105, 'JUD'), 
('V', 'creature', '3VV', 3, 3, 'Daren Bader', 0, 106, 'JUD'), 
('V', 'creature', '3V', 3, 3, 'Matt Cavotta', 1, 107, 'JUD'), 
('V', 'ephemere', 'V', NULL, NULL, 'Matthew Mitchell', 0, 108, 'JUD'), 
('V', 'creature', '3V', 2, 2, 'Eric Peterson', 0, 109, 'JUD'), 
('V', 'rituel', '6VVV', NULL, NULL, 'Christopher Moeller', 2, 110, 'JUD'), 
('V', 'enchantement', '2V', NULL, NULL, 'Jim Nelson', 1, 111, 'JUD'), 
('V', 'enchantement', '2VV', NULL, NULL, 'Greg & Tim Hildebrandt', 2, 112, 'JUD'), 
('V', 'creature', '3V', 4, 5, 'Greg Staples', 2, 113, 'JUD'), 
('V', 'enchantement', '1V', NULL, NULL, 'Wayne England', 1, 114, 'JUD'), 
('V', 'ephemere', '2V', NULL, NULL, 'Matt Cavotta', 0, 115, 'JUD'), 
('V', 'creature', '1V', 2, 1, 'Darrell Riche', 1, 116, 'JUD'), 
('V', 'creature', '4V', 4, 4, 'Mark Zug', 2, 117, 'JUD'), 
('V', 'creature', '5V', 5, 5, 'Kev Walker', 0, 118, 'JUD'), 
('V', 'rituel', '3VV', NULL, NULL, 'Dave Dorman', 1, 119, 'JUD'), 
('V', 'creature', '1V', 1, 1, 'David Martin', 0, 120, 'JUD'), 
('V', 'creature', '1V', 1, 1, 'Heather Hudson', 0, 121, 'JUD'), 
('V', 'ephemere', '1V', NULL, NULL, 'Gary Ruddell', 1, 122, 'JUD'), 
('V', 'creature', 'V', 1, 1, 'Edward P. Beard, Jr.', 0, 123, 'JUD'), 
('V', 'rituel', '1V', NULL, NULL, 'Eric Peterson', 2, 124, 'JUD'), 
('V', 'creature', '1V', 2, 1, 'Greg Staples', 0, 125, 'JUD'), 
('V', 'creature', '2V', 2, 3, 'Darrell Riche', 0, 126, 'JUD'), 
('V', 'creature', '2VV', 2, 0, 'Carl Critchlow', 1, 127, 'JUD'), 
('V', 'creature', '2V', 0, 0, 'Wayne England', 2, 128, 'JUD'), 
('V', 'creature', '2V', 1, 0, 'Brian Snoddy', 0, 129, 'JUD'), 
('V', 'ephemere', '1V', NULL, NULL, 'Rebecca Guay', 2, 130, 'JUD'), 
('V', 'ephemere', 'XV', NULL, NULL, 'David Martin', 1, 131, 'JUD'), 
('V', 'ephemere', '3V', NULL, NULL, 'Alan Pollack', 0, 132, 'JUD'), 
('V', 'creature', 'V', 1, 1, 'Pete Venters', 2, 133, 'JUD'), 
('V', 'creature', '5VV', 5, 5, 'John Avon', 2, 134, 'JUD'), 
('V', 'creature', '6VV', 6, 6, 'Jeff Easley', 1, 135, 'JUD'), 
('V', 'rituel', '2VV', NULL, NULL, 'Ron Spencer', 0, 136, 'JUD'), 
('M', 'creature', '1VW', 3, 4, 'Arnie Swekel', 2, 137, 'JUD'), 
('M', 'enchantement', 'VW', NULL, NULL, 'Mark Brill', 2, 138, 'JUD'), 
('M', 'enchantement', '3VW', NULL, NULL, 'David Martin', 2, 139, 'JUD'), 
('M', 'creature', '5VW', 0, 0, 'Arnie Swekel', 2, 140, 'JUD'), 
('T', 'terrain', 'T', NULL, NULL, 'Tony Szczudlo', 1, 141, 'JUD'), 
('T', 'terrain', 'T', NULL, NULL, 'Rob Alexander', 1, 142, 'JUD'), 
('T', 'terrain', 'T', NULL, NULL, 'Don Hazeltine', 1, 143, 'JUD');

