INSERT INTO POSSESSION (POS_QUANTITE, CARTE_ID, LANG_ID, COL_ID) VALUES (3, 12, 1, 1);
INSERT INTO POSSESSION (POS_QUANTITE, CARTE_ID, LANG_ID, COL_ID) VALUES (2, 2, 1, 1);
INSERT INTO POSSESSION (POS_QUANTITE, CARTE_ID, LANG_ID, COL_ID) VALUES (4, 94, 2, 1);
INSERT INTO POSSESSION (POS_QUANTITE, CARTE_ID, LANG_ID, COL_ID) VALUES (1, 50, 1, 1);
