INSERT INTO LANGUE_SERIE (LANG_ID, SER_CODE) VALUES (1, 'JUD');
INSERT INTO LANGUE_SERIE (LANG_ID, SER_CODE) VALUES (1, 'KLD');
INSERT INTO LANGUE_SERIE (LANG_ID, SER_CODE) VALUES (1, 'ODY');
INSERT INTO LANGUE_SERIE (LANG_ID, SER_CODE) VALUES (1, 'TOR');
INSERT INTO LANGUE_SERIE (LANG_ID, SER_CODE) VALUES (2, 'KLD');
